### ISSUE TITLE
Add subset by mode

### ISSUE THREAD

**Issue by j-harbin** [ArgoCanada/argoFloats#112]
As discussed in the vftf with @dankelley , we are going to add subset by `mode`, meaning `realtime` or `delayed`. It would look like this : `subset(ai, mode='realtime')`. I will be using Dan's `grep()` code in his sandbox to incorporate this.

**Comment by j-harbin** [comment]
@dankelley , I have made a commit ( #a383918) to the `issue112` branch . I am not quite there yet, but I know I am close. Would you take a look at this when you get a moment?

**Comment by dankelley** [comment]
I think you're on the right track.  A few things:
* minor: in a terminal, try `git grep -n " $" R` in the top level will tell you about lines with a space at the end.  This is minor, but I always delete trailing whitespace without checking, and we don't want some lines authored by you on a particular date being reauthored by me later, because authorship/date is a good tool that git provides for finding bugs.
* minor: please write `if (...` and not `if(...` because uniformity of notation makes it easier to search through code.  (This is why I remove whitespace at the end, also ... for example, I grep for `{$` a lot, to find the starts of blocks, and that pattern breaks if there is a space after the `{`
* major: near the centre, you spell `as.character()` incorrectly.  Also, you will want to check which one we have, using something like the following, after you checked that i
```R
if (mode == "delayed") {
   keep <- grepl("^[a-z]*/[0-9]*/profiles/.{0,1}D.*$", x[["file"]])
} else if (mode == "realtime") {
   keep <- grepl("^[a-z]*/[0-9]*/profiles/.{0,1}R.*$", x[["file"]])
} else {
   stop("In subset,argoFloats-method() : 'mode' must be character containing 'realtime' or 'delayed'")
}
x@data$index <- x@data$index[keep, ]
```



<img width="1050" alt="Screen Shot 2020-05-29 at 12 43 45 PM" src="https://user-images.githubusercontent.com/99469/83278653-502f2280-a1aa-11ea-84c4-ae1f4007efd4.png">

**Comment by dankelley** [comment]
Sorry, closed by mistake.

**Comment by j-harbin** [comment]
Added in commit #a0add1c of the develop branch with the help of Dan in a vftf. I am therefore closing this issue.
