### ISSUE TITLE
Make getIndex() age command detect if delayed files have been changed

### ISSUE THREAD

**Issue by j-harbin** [ArgoCanada/argoFloats#139]
As discussed in the vftf with Dan, Clark, Chris and Blair, it would be a good idea when using the age command in `getIndex()` for it to detect if delayed files have been changes when caching.

**Comment by dankelley** [comment]
I suggest we work on this in paired-coder mode in a vf2f meeting.

**Comment by dankelley** [comment]
I think this must mean `getProfiles()`,  not `getIndex()`.  Is that right, @j-harbin?  If so, please edit the subject line.  Also, perhaps edit the title to be more direct and specific, e.g. perhaps `"getProfiles() should have an 'age' argument"`.

I think the chance of code changing will be higher if the issue title is more concrete.

**Comment by j-harbin** [comment]
I think this was more referring the following code, for example,

```R
library(argoFloats)
if (!exists("i"))                      # cache for interative tests
    i <- getIndex()
```

Would this pick up if a real time ID turned to Delayed mode (ie. aoml/1901584/profiles/R1901584_124.nc to aoml/1901584/profiles/D1901584_124.nc) ?

**Comment by dankelley** [comment]
Yes, if the `getIndex()` was called more than a day ago, the new index will be downloaded into the `destdir` directory, and it will point to the most recent filenames, so if `getProfiles()` is called, and there is a file that was not previously downloaded, then `getProfiles()` will download it.

I think the issue came up because we learned (from @cgrdn, I think) that a given file on the server might get updated at any time.  So, adding an `age` argument to `getProfiles()` would be a way to ensure that we got a new version of the file, if the most recent download was more than `age` days ago.

Another approach would be to retain the old index and compare the `date_update` fields, but I do not favour that method because then the user (or the package) would need to save old index files and keep track.  For example, if a user asks for a file name `x.nc` then argoFloats would have to check the date of last download, find an index file with the same date, look up the `date_update` value, and then decide whether to re-download.  That all sounds very complicated, an I prefer the straightforward approach, where e.g. now
```R
i <- getIndex()
is <- subset(i, SOME_CRITERION_HERE)
p <- getProfiles(is)
```
will use previously-downloaded netcdf files if they exist, and
```R
i <- getIndex()
is <- subset(i, SOME_CRITERION_HERE)
p <- getProfiles(is, age=1)
```
would re-download any netcdf files that were downloaded more than a day ago.

I might be inclined to set a default of age=10 or something, to prevent a lot of downloads.  But, as with many things argo, I have little idea of how things actually; absent clear documentation, we always have to make assumptions (as with this nagging question in #179 about how to interpret oddly-configured QC hex digits)

**Comment by cgrdn** [comment]
Yes - pasting this from Isabelle re: how often files change: 

> The R- and D- files do change fairly regularly. Floats should be DMQC’d at least yearly and preferably every six months for the core-Argo files, and so each of the floats should (ideally) be getting new D files at least that often. For the DOXY there’s been talk of updating adjustments every few months, and smaller fixes can also happen more often in response to anomaly reports. For the purposes of DMQC I typically fetched the latest files any time I was working with a float; if you’re trying to maintain an up-to-date set to work with I’d suggest something like a monthly update. But obviously that depends on your application, as it’s obviously a largeish download.

This might be overkill because the age argument makes a lot of sense to me and downloads generally aren't that slow, but you could also compare the last modified time of the local file to the `date_update` field from the index? In (kind of) python: 

```python
from time import time
from pathlib import Path
import pandas as pd

# get the global index
df = pd.read_csv('ar_index_global_prof.txt.gz', compression='gzip', header=8)
# local profile file
fn = '/Path/to/local/file.nc'
# get time when file was last modified locally, in seconds
modified_time = Path(fn).stat().st_mtime
# get how old the file is in days
age = (time() - modified_time) / 60 / 60 / 24

if age > 10:
    # check against global index (you'd have to convert both these to be comparable, but the point is there
    if modified_time < df.date_update:
        # then re-download the file here
```

I haven't done it yet but I'll probably end up implementing something like this in [bgcArgo](https://github.com/ArgoCanada/BGC-QC), right now I just have a T/F `overwrite` parameter.

**Comment by dankelley** [comment]
@cgrdn Thanks for this comment.

Since I do not know *for sure* what the `date_update` field means and whether I can trust it to be accurate without having a citation to a subsection in an official Argo document at a stable website<sup>1</sup>, I prefer to work with age-of-file (as in what you've written), because we already do for `getIndex()`, so the code is written already and the scheme will be familiar to users.

To @j-harbin and @richardsc, with `age` added, `force` will no longer be required (`force=TRUE` would be equivalent to `age=0` and `force=FALSE` would be like `age=100`) so I propose that @j-harbin and I will remove the `force` argument, unless either @j-harbin or @richardsc objects (by 0900 next Tuesday, to be concrete).

1. @richardsc and I learned in the `oce` project (github.com/dankelley/oce) that it helps a lot to write code that is tied to official documentation.  That saves coding time and it makes it easier for the user to learn more.  Plus, when a file structure (or URL framework) is not documented in an official way, it may be subject to drift, which forces everyone to keep up.

**Comment by dankelley** [comment]
(Action for @j-harbin at the end.)

**Background**

Hm. Actually, `getIndex()` is wholly independent of any files that might have been downloaded with `getProfiles()`, and so the action cannot (or should not) involve looking at the age of previously-downloaded netcdf files.

That leaves the matter of comparing with indices that had been downloaded by previous calls to `getIndex()`.  This seem not to be very useful, partly because it imposes upon the user the responsibility for keeping track of when they did that action.

These arguments suggest a certain lack of need for the requested feature, for `getIndex()`.

So, maybe this applies to `getProfiles()` ... ?   At the moment, we have an argument called `force`, which forces a re-download for all files.  I propose adding a new arg called `age`, which checks the age of the downloaded netcdf file, and downloads it again if the age is exceeded.  This is nothing to do with whether the index has changed, but I think it would be useful.  

**ACTION** @j-harbin, if you think this makes sense, can you close this issue, and open a new one with a similar title, but with `getProfiles()` in it.  And I think the default age ought to be 365 days, based on vf2f discussions with others, about the timing of delayed-mode updates, etc.

**Comment by j-harbin** [comment]
This is a great explanation, thanks for this. I think that all makes sense. I will close this issue and create a new issue pertaining to `getProfiles()`.
