### ISSUE TITLE
Prebuild vignette

### ISSUE THREAD

**Issue by j-harbin** [ArgoCanada/argoFloats#162]
As discussed with Dan in a vftf, a good idea is to prebuild the vignettes before submitting to CRAN. One website that may be helpful is https://stackoverflow.com/questions/30976308/how-do-i-prebuild-a-vignette-index-for-an-r-package

**Comment by dankelley** [comment]
A good source for this is https://cran.r-project.org/web/packages/R.rsp/vignettes/R_packages-Static_PDF_and_HTML_vignettes.pdf

**Comment by j-harbin** [comment]
Dan,

If you look at commit 0ee0f0fa4a1e732c4db04ee6f9526243110140b8 of branch issue162, I have completed the steps suggested by your link. The problem I am running into is when trying to build into a pdf, it doesn't "like" the quality control flow chart. More specifically, this is what I receive:

![Screen Shot 2020-06-30 at 11 44 58 AM](https://user-images.githubusercontent.com/58750538/86140375-2c237180-bac7-11ea-92af-b6a8e1082727.png).

I also tried trying to simply include a png of the flow chart instead of the code, however, when I do the standard
![]() format to add an image, that also doesn't work.

Any suggestions?

**Comment by dankelley** [comment]
Can you list the precise steps you took, one by one, so I can try to reproduce error?

**Comment by j-harbin** [comment]
1. Moved the qc.Rmd file to the vignette directory
2. Added the following lines to the beginning of the Rmd:
output:
  pdf_document: default
  html_document:
    df_print: paged
vignette: |
  %\VignetteIndexEntry{Introduction to argoFloats Quality Control} %\VignetteEngine{R.rsp::asis} %\VignetteEncoding[utf-8]{inputenc} %\VignetteKeyword{PDF} %\VignetteKeyword{HTML} %\VignetteKeyword{vignette} %\VignetteKeyword{package}
3. Added R.rsp to the suggests and VignetteBuilder section of DESCRIPTION
4. Tried to build into a pdf and received the error shown in the comment above.

**Comment by dankelley** [comment]
I can verify your error.  FYI, I tried the last step with
```R
rmarkdown::render("qc.Rmd", "pdf_document")
```
I'll look into it.

**Comment by dankelley** [comment]
Hm.  If I just remove that diagram, it builds.

**Comment by dankelley** [comment]
I pulled the diagram out, and built it separately.  Now, when I do
```R
 Rscript -e 'rmarkdown::render("qc.Rmd", "pdf_document")'
```
it builds `qc.pdf` properly.

I put `flowchart.png` into the git repo, so there is no need to rebuild it.

@j-harbin maybe you can try rebuilding (please do it in the unix commandline, as indicated above, because then it's super-easy to explain the procedure).  Our next step will be to see if this "carries over" so that a user can see the qc vignette.  And then we'll need to see if pkgdown "notices" this setup.  Frankly, though, I want our vignettes *within the R ecosystem* to work, and whether the pkgdown works is not as important to me.

**Comment by j-harbin** [comment]
I can confirm this works for me. I tried a similar approach with putting a flowchart png into the directory, however, where I went wrong was adding the .png to the filename. This is very helpful.

**Comment by j-harbin** [comment]
Just to confirm, is the final step before closing this issue to merge with master and see if pkgdown picks it up for building the website?

**Comment by dankelley** [comment]
Oh, I forgot where we were on this, so thanks for the reminder

I think there are quite a few stages.

**PHASE 1**

**Step 1.**

In rstudio, unclick the button that causes vignettes to be built, since we will henceforth be required to build them manually with
```
Rscript -e 'rmarkdown::render("qc.Rmd", "pdf_document")'
```
in the unix shell.  (There is a way to do this in rstudio also, but I think it's easier and more reproduceabe to use the shell.)

**Step 2.**

Add the "asis" file, following the procedure at https://cran.r-project.org/web/packages/R.rsp/vignettes/R_packages-Static_PDF_and_HTML_vignettes.pdf

**PHASE 2**

At this stage, the vignette is okay.  The following steps are general, and apply whenever we want to update the webpages.  The key is that (I think) we are set up so we must update the webpages from "master", not "develop".

**Step 1.**

Get things working in "develop".  ("Working" means that the package builds, tests and checks, and that this procedure is *not* updating the vignette.  From now on, we want vignettes only to be built when we say so.  This will let us download data so we can illustrate more interesting things, without inviting CRAN rejection.)

**Step 2.**

Once "develop" is OK, update "master", then merge "master" into "develop" and recheck.  This step catches new features in "master", and it also helps to prevent terrible "merge conflict" problems in the next step.

**Step 3.**

At this stage, both "develop" and "master" build cleanly.  So, we should not cause problems by merging "develop" into "master".  So, do that, and again build/test/check.

**Step 4.**

Now, "master" has the new features from "develop".  In fact, they should be identical.  I suggest checking out "master" and doing "git diff develop" to ensure that there are no differences.  If there are, it's time to stop and think, before wrecking anything!

**Step 5.**

With "master" checked out, do the following in the shell
```
Rscript -e "pkgdown::build_site()"
```
to build up the site.  If there are any errors, stop now and discuss with co-developers!

**Step 6.**

Push "master" to github.  This should update the webpage.  Check (after waiting a minute or two) and if there are errors (e.g. something not updated) then contact co-developers.

**Step 7.**

Assume all of the above has worked, check out "develop" and merge "master" into it.

That's it.  Easy peasy.  Well, maybe not ... I may have some steps wrong!  

We could do this in a vf2fm if you like.  I'd love to get the instructions clear (and correct) so we can put them in the wiki, for future work.  I have burned up hours by getting tangled in knots with merge conflicts whilst trying to do this kind of work.

**Comment by j-harbin** [comment]
I agree, I think this would be a great thing for us to work together on and then I will create the wiki. I am available for a vftf at your convenience today.

**Comment by dankelley** [comment]
Is 0900h ok for you?

**Comment by j-harbin** [comment]
From commit 0507f1ab3eef1bf4146e85f5117156f79e9685e1 to commit 097472863b3ed76050a6f04328b278f231c3ec4b in the develop branch, @dankelley and I worked on the prebuilt vignette. We then decided instead to create png files for the vignettes (to avoid the need to download data). In issue 129 I will explains the steps of this. I am therefore closing this issue.
