### ISSUE TITLE
Error in tools::buildVignette

### ISSUE THREAD

**Issue by j-harbin** [ArgoCanada/argoFloats#166]
Hi Team,

I ran into something interesting, when I do Build>Configure Build Tools> Configure> click YES to Vignettes the "Check" works fine, however, the "Clean and Rebuild" produces the following error:

![Screen Shot 2020-07-03 at 7 31 36 AM](https://user-images.githubusercontent.com/58750538/86460780-5f504580-bcff-11ea-86d8-bb65666d847b.png)

When the vignettes are left unclicked, I do not receive this error.

**Comment by dankelley** [comment]
Hm.  I do not get that error when I pull this, an select the "Build/More/Clean and Rebuild" menu item of the environment/history/connections/build/git/tutorial panel in RStudio.  (Wow, it's hard to say what you do in RStudio.)

I could do a quick Z if it would help.  I have another at 0900 though.

**Comment by j-harbin** [comment]
Right now in the latest commit, the 'vignettes' tab is not clicked under Build>Configure Build Tools> Configure. However, when it is, that's when I receive the error. I'm wondering if you unclicked it before trying the "Build/More/Clean and Rebuild". Thanks!

**Comment by dankelley** [comment]
Hm, if I had actually *read* your comment, I'd have seen what you saw.   I'm not sure what's going on, but I have had encoding problems before, and I know there are ways to solve it:
1. tell R that you are using another encoding (I thought we did that though...)
2. only use ASCII encoding

The second seems the best.  Here's how I found the bad lines:
```R
> library(tools)
> showNonASCIIfile("vignettes/qc.Rmd")
53: As described by the Argo user<e2><80><99>s manual [2], data that are given a flag value of
291: 2. Carval, Thierry, Bob Keeley, Yasushi Takatsuki, Takashi Yoshida, Stephen Loch Loch, Claudia Schmid, and Roger Goldsmith. Argo User<e2><80><99>s Manual V3.3. Ifremer, 2019. https://doi.org/10.13155/29825.
```

The problem is in the "'" character.  When we cut/paste from zotero, we get a non-ASCII character for that.  (I cannot type it because I don't know what keys to strike to get that.)  I changed them to normal "'" characters (what we call single-quote) and pushed to "develop" commit 89f74e64f87f0bded86387b1e388c48c4c5fc81e and all should work.

I also (in another commit after the one mentioned) added `.html` to the `.gitignore` in `vignettes`.

**Comment by dankelley** [comment]
At https://www.utf8-chartable.de/unicode-utf8-table.pl?start=8192&number=128 you can see that e2-80-99 (see my prev comment) is indeed a "RIGHT SINGLE QUOTATION MARK".

**Comment by dankelley** [comment]
Also, in case it's of help for other things,
```R
git diff 'develop@{1 week ago}..develop' -- qc.Rmd
```
tells us how qc.Rmd has changed in the past week.  This can be easier than dong `git log` and noting commit hashcodes.

**Comment by j-harbin** [comment]
Thanks for this! I can confirm I no longer receive the error. I am therefore closing this issue.
