### ISSUE TITLE
How to determine which QC tests were performed and failed using HISTORY_QCTEST

### ISSUE THREAD

**Issue by j-harbin** [ArgoCanada/argoFloats#176]
Hi @cgrdn,

In the following R code:

```R
library(argoFloats)
library(oce)
index1 <- subset(getIndex(), profile="188")
index2 <- subset(index1, ID='3900407')
profiles <- getProfiles(index2)
argos <- readProfiles(profiles)
showQCTests(argos[[1]])
```
The output is as follows:

```R
Tests performed: 1 2 3 4 5 6 7 8 9 11 12 13 14 15 16 17 18 19
Tests failed:    2
```
Test 2 is the "Impossible Date Test". An Argo fails this test if the JULD date is not between 1950-01-01 and the day of check (today). Using the newly developed functions in oce, timeToArgoJuld and argoJuldToTime, which consider the JULD time with a reference of 1950-01-01, we see that to not be the case, however:

```R
timeToArgoJuld("1950-01-01")
start <- argoJuldToTime(0)
argoJuld <- argos[[1]][['juld']]
argo <- argoJuldToTime(argoJuld)
today <- timeToArgoJuld(Sys.time())
time <- argoJuldToTime((today))
cat(paste0(start), paste0(argo), paste0(time), sep=", ")
```

This has us reconsidering if the `showQCTests()` in `argoFloats` is reading the hexadecimal in the right direction from HISTORY_QCTEST. Can you provide any thoughts on this?

**Comment by cgrdn** [comment]
Hi @j-harbin, 

I’m still learning my way around these QC history/action variables just as you are – so I have some ideas that I’ll put below but by no means am I totally certain of them. 

I loaded that profile in on my own and didn’t see any issue with the date either. I thought that maybe since it was a delayed mode file the date could have been interpolated and filled in, but the JULD_QC flag is set to 1 (not 8) so that doesn’t seem to be the case either. I also looked at if maybe the date for cycle 188 was before the date for 187, but no luck there either. 

If you’re reading that QCF row of HISTORY_QCTEST as 4000, then 4000 base 16 = 4*16^3 = 16384, which corresponds with test 14, implying it failed the density inversion test. I don’t know if there’s a way to look at that since the values are now removed/masked out, but there are 3 PSAL values flagged as bad, so that is at least more in line with the data I think. So then I tried to decode the QCP row, which is FFBFE = 1047550 = 1044576 + 2048 + 512 + 256 + 128 + 16 + 8 + 4 + 2, which is tests 20, 11, 9, 8, 7, 4, 3, 2, 1. That also seems to make sense because it is an older float that was using Argos not iridium (https://fleetmonitoring.euro-argo.eu/float/3900407). This doesn't match with your answer, but I'm just working by hand here. 

In python I read in the hexadecimal code from HISTORY_QCTEST as:

```
python
qctest_decimal = int('FFBFE', 16) # returns 1047550
```

I haven't coded actually deciphering the decimal number to get the test numbers yet - working on that now.

**Comment by dankelley** [comment]
I'll make some R notes here.

**Test 1.**
```R
> rawToBits(as.raw(0xFE))
[1] 00 01 01 01 01 01 01 01
> rawToBits(as.raw(0x03))
[1] 01 01 00 00 00 00 00 00
```
tells us that R reverses bits with a given byte, compared with what I'll call "math notation.

**Test 2.**
```R
> rawToBits(c(as.raw(0xFE), as.raw(0x01)))
 [1] 00 01 01 01 01 01 01 01 ... 01 00 00 00 00 00 00 00
```
tells us that R does *NOT* reverse bits from byte to byte.  (Look closely and you'll see this. To help, I inserted a "..." to separate the 8-bit chunks.)

Now, note that we have an odd number of hex characters.  R only defines "raw" items with two characters each -- think of that as being byte-focussed -- so we need to devise a way to get the 4 bits for a single hex character.  (PS. a 4-bit chunk is called a "nibble").  Suppose want to decode hex "C" (dec 12), which we know is 1 1 0 0 (for 8 + 4).  We can get that as follows

**Test 3.**
```R
> rawToBits(as.raw(0x0C)) # note that bits are reversed
[1] 00 00 01 01 00 00 00 00
> rev(rawToBits(as.raw(0x0C))) # reverse bits to get math notation
[1] 00 00 00 00 01 01 00 00
> tail(rev(rawToBits(as.raw(0x0C))), 4) # discard first 4 (zero) bits
[1] 01 01 00 00
```
so we can write a little function
```R
rawToNibble <- function(h)
    tail(rev(rawToBits(as.raw(paste0("0x0", h)))), 4)
```
let's test it, first for case
```R
rawToNibble("c")
rawToNibble("C")
```
and then for all the possible hex digits.
```R
rawToNibble("c")
rawToNibble("c")
rawToNibble("c")
rawToNibble("c")
rawToNibble("c")

**Comment by dankelley** [comment]
NOTE to @j-harbin @cgrdn and @richardsc -- this is an empty issue comment, which I will delete in a moment.  It's just a way to get github to email you to say that I am finished with altering the comment that completes what you saw in your previous email.  (I hit some character and closed the input-text dialog box by mistake. Then I edited it to complete it.)

**Comment by dankelley** [comment]
Oh, sorry, I see the problem.  Test 1 corresponds to bit 2.  My code now gives that test 14 failed, just as @cgrdn's code does:
```R
> rawsToNibbles <- function(h) {
+     res <- NULL
+     for (hh in strsplit(h, "")[[1]]) {
+         bits <- ifelse(01 == rawToBits(as.raw(paste0("0x0", hh))), 1, 0)
+         res <- c(res, tail(rev(bits), 4))
+     }
+     res
+ }
> rawsToNibbles("4000")                  # in math order
 [1] 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0
> rev(rawsToNibbles("4000"))             # in order of tests
 [1] 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0
> n <- rev(rawsToNibbles("4000"))        # in order of tests
> data.frame(test=seq_along(n)-1, done=n)
   test done
1     0    0
2     1    0
3     2    0
4     3    0
5     4    0
6     5    0
7     6    0
8     7    0
9     8    0
10    9    0
11   10    0
12   11    0
13   12    0
14   13    0
15   14    1
16   15    0
```

**Comment by cgrdn** [comment]
Looks good to me. Seems like in my initial comment there was a typo in the manual (for test 20, 2^20 = 1048576 not 1044576, I was looking at version 2.4 for reference). Python code below agrees with yours. I have a feeling there's a cleaner/possibly more efficient way to do this but its fast and correct either way.

```python
def decode_qctest(hex_code):
    # hex to numeric
    num = int(hex_code, 16)
    # list to save test number in
    tests = []
    for i in range(22,0,-1):
        qc_binary_id = 2**i
        if qc_binary_id <= num:
            num -= qc_binary_id
            tests.append(i)
    
    return tests, num

def print_result(tests, remainder):
    print('Tests performed: ', end='')
    for t in tests[::-1][:-1]:
        print('{:d}, '.format(t), end='')
    print('{:d}'.format(tests[0]))
    print('Remainder (should be 0): {:d}'.format(remainder))

# get test numbers and print them out
print('FFBFE:')
print_result(*decode_qctest('FFBFE'))
print('\n4000:')
print_result(*decode_qctest('4000'))
```

**Comment by j-harbin** [comment]
@cgrdn , Dan and I have made some changes in commit 7c01ce703d844afd9180b74e411793b826c0b5ff of the develop branch for `argoFloats`. We now get the same answer as you!

**Comment by dankelley** [comment]
Closing, as per vf2f JH/DK today.
