### ISSUE TITLE
getProfiles() should have an age arg

### ISSUE THREAD

**Issue by j-harbin** [ArgoCanada/argoFloats#214]
As discussed in issue https://github.com/ArgoCanada/argoFloats/issues/139, `getProfiles()` should have an `age` arg, with a default of about 1 year.

**Comment by dankelley** [comment]
I plan to also remove the `force` argument because
1. it is superceded by `age`, because using `age=0` is equivalent to `force=TRUE`
2. we never discussed it in a video, or in a vignette
3. having two args that do nearly the same thing (and that can conflict) is confusing to the user

@j-harbin OK, boss?

**Comment by j-harbin** [comment]
That all seems logical to me!

**Comment by dankelley** [comment]
Done in "develop" commit d9e29981ed1dc22e72f7cf4b7ca65217557c16ed
