### ISSUE TITLE
Bug when plotting which='map'

### ISSUE THREAD

**Issue by j-harbin** [ArgoCanada/argoFloats#227]
Doing the following code produces a not so lovely plot:
```R
library(argoFloats)
library(ocedata)
library(oce)
par(mar=c(3,3,1,1))
data("coastlineWorldMedium")
ai <- getIndex()
from <- as.POSIXct("2019-07-01 00:00:00", tz="UTC")
to <- as.POSIXct("2019-07-02 00:00:00", tz="UTC")
subset <- subset(ai, time=list(from=from, to=to))
plot(subset)
```

![Screen Shot 2020-09-03 at 12 00 22 PM](https://user-images.githubusercontent.com/58750538/92132101-1b4fee80-eddd-11ea-84b9-753c7e387acb.png)

**Comment by dankelley** [comment]
Thanks. TO solve this, I am going to back-port the new method I have for axes (used in a teaching app).

**Comment by dankelley** [comment]
I've tried to fix this, in "develop" commit 0f23f91c387e746f5509dac9636dd533eb8098fd

Can you check it, @j-harbin?  A good starting point is to run the code in `issues/2x/227/227.R`.

This was tricky to code because there are so many test cases, e.g.
* is bathymetry requested?
* were `xlim` and `ylim` given?
* do the data extend across the world or only a small portion?

and so forth.  Each one has 2 choices, so coding for *n* items takes effort proportional to *2^n*, and the same for testing.  Two items, not too hard.  Four items, harder, Eight items, getting pretty nasty now... I only checked for the first two items in this test file.  Oh, and the other is that the user might have given `par(mar)`, which could make for ugly results ... I didn't really play with that, hoping that the old code was okay.

I will likely back-backport this into oce/R/coastline.R at some point.

**Comment by j-harbin** [comment]
Hi Dan,

Thanks for getting this done so quickly. One thing I will note, I when running the code in `227/227.R`, when `bathymetry=TRUE`, aka for `plot(subset)` I receive the following plot where the bathymetry colour bar is not lined up with the plot:

![Screen Shot 2020-09-03 at 2 05 12 PM](https://user-images.githubusercontent.com/58750538/92145518-b9988000-edee-11ea-8163-cef983f12f40.png)

Also, I know you are working on your app, so no rush on this.

**Comment by dankelley** [comment]
Can you pull and use "make" in that directory?  I don't get the palette on top of the plot, but it does extend far above and below it.  Exactly what happens will depend on the device geometry and the `par("mar")` setting.

I can make the palette fit the same "y" space as the plot, I think.

**Comment by j-harbin** [comment]
Closing as discussed with @dankelley.
