### ISSUE TITLE
TS diagram after applyQC plotting red points when it shouldn't

### ISSUE THREAD

**Issue by j-harbin** [ArgoCanada/argoFloats#243]

**Comment by dankelley** [comment]
Below is a screenshot that is a note to myself, for when I look at this later today.  The problem is that oce defaults to "bad" flags of 0, 3, 4, and 9.  But argoFloats is saying that 0 (which means not assessed) is acceptable.  I think that's the cause of the discrepancy between what `applyQC()` is doing and the colourizing by `plot`.  I'll add more here later today, probably.

<img width="1050" alt="Screen Shot 2020-09-15 at 10 56 10 AM" src="https://user-images.githubusercontent.com/99469/93219785-1aef1600-f742-11ea-8244-e7a9d0188bae.png">

**Comment by dankelley** [comment]
The docs for `applyQC()` state
```
#' 0 (for data that have not yet been assessed),
#' 3 (for "probably bad" data),
#' 4 (for "bad" data),
#' 6 (an unused flag),
#' 7 (an unused flag), or
#' 9 (for "missing" data).  See Sections 3.2.1 and 3.2.2 of Carval et al. (2019) for
#' more information on these QC code values.
```

**Comment by dankelley** [comment]
This is fixed now.  You need to rebuild oce and argoFloats for it to work.  Doing
```
make 08_applyQC.out
```
creates as attached.  Please note that

1. I removed this `.png` from the repo, and altered `.gitignore` to not store future `.png` files.  The repo should not store those files, which are produced from the R code.
2. I made `08_applyQC.R` cache the data in a local `.rda` file.  This is helpful because then rerunning the code takes sub-second, as opposed to (potentially) several minutes for downloading an index, etc.  I put the `.rda` into the git repo, so other authors won't need to download not just the index, but all those .netcdf files.

Regarding point 2, I always advise caching data this way.  Otherwise, the inevitable work to tweak diagrams gets very time-consuming.  If we want, we can just remove the `.rda` files and do 'make clean', followed by 'make', and that gives a complete refresh.

PS. I am pretty sure the journal will require PDFs for the figures, not PNGs.  I wonder if we are using PNG because markdown likes that format.  If so, that would be yet another reason why I'd vote to just switch to latex.  Rebuilding a lot of figures at submission time is just boring work, especially since quite often the font sizes won't quite be what is desired, etc.  (I know this because of the whale paper ...)


![08_applyQC](https://user-images.githubusercontent.com/99469/93253817-cb264400-f76d-11ea-9992-4286fba7e510.png)

**Comment by j-harbin** [comment]
Thanks for fixing this, Dan. As for the png to pdf issue, this is something we should discuss in out vftf tomorrow. I am closing this issue.
