### ISSUE TITLE
Method overwriting warning

### ISSUE THREAD

**Issue by richardsc** [ArgoCanada/argoFloats#244]
![image](https://user-images.githubusercontent.com/233584/93471234-78fa3580-f8c9-11ea-84bb-aa487fa32e19.png)

**Comment by dankelley** [comment]
Thanks.  As you said in our vf2fm today, this message is not an `argoFloats` thing, nor an `oce` thing, since the message without using either (see below, with R 4.0.2).

Therefore, I will close this issue.  I am glad to have it in the closed-issue section, in case an `argoFloats` (or `oce`) user asks about it this message.
```
➜  ~ cat 0.R
library(marmap)
➜  ~ Rscript 0.R
Registered S3 methods overwritten by 'adehabitatMA':
  method                       from
  print.SpatialPixelsDataFrame sp
  print.SpatialPixels          sp

Attaching package: ‘marmap’

The following object is masked from ‘package:grDevices’:

    as.raster
```
