### ISSUE TITLE
Do Argo oxygen profiles always have the unit "umol/kg"?

### ISSUE THREAD

**Issue by j-harbin** [ArgoCanada/argoFloats#266]
This question came up in a vftf with @dankelley. I did some investigating and my answer, is yes. Oxygen profiles always have the unit `umol/kg`. My reasoning is as follows:

On page 80, section 3.2.2 of the Argo User's Manual[1] , it states the following (shown in a screenshot)

![Screen Shot 2020-10-16 at 1 03 02 PM](https://user-images.githubusercontent.com/58750538/96281608-f17b1180-0faf-11eb-9a1c-2fd32346d602.png)

Additionally, on page 71 of the Argo User's Manual [1], in the "B-Argo parameters" table, when "DOXY" is listed, under "units" it says "mol/kg".  A screenshot is provided below:

![Screen Shot 2020-10-16 at 12 58 47 PM](https://user-images.githubusercontent.com/58750538/96281280-7fa2c800-0faf-11eb-9613-78391f501f26.png)

Dan, if you are satisfied with this answer, please feel free to close this issue.

[1] Carval, Thierry, Bob Keeley, Yasushi Takatsuki, Takashi Yoshida, Stephen Loch Loch, Claudia Schmid, and Roger Goldsmith. Argo User’s Manual V3.3. Ifremer, 2019. https://doi.org/10.13155/29825.

**Comment by j-harbin** [comment]
Maybe @cgrdn 's expertise is this area would be useful. Do you have any input on this, Chris?

**Comment by dankelley** [comment]
Wow,  one column says moles per unit mass (thus mol/kg) and the other column says micromol/kg.  I continue to be amazed by the spotty quality of official argo documentation.

I think it would make sense (for our package) to test maybe 100 random files by e.g.
```R
library(argoFloats)
ncheck <- 100
i <- getIndex("bgc")
nprofiles <- i[["length"]]
look <- sample(1:nprofiles, ncheck)
print(look)
a <- readProfiles(getProfiles(subset(i, look)))
units <- unlist(lapply(a[["argos"]], function(x) as.character(x[["oxygenUnit"]]$unit)))
cycles <- a[["cycle"]]
IDs <- a[["ID"]]
for (i in 1:ncheck) {
    cat(IDs[i], cycles[i], as.character(units[i]), "\n")
}
```
then we might get an idea of how uniform the units are.

I am finding that some files have no oxygen units, but I've not looked in detail to see why.  I have no time to look more into this but I think the issue ought to remain open until maybe @cgrdn can say definitively what the oxygen unit is (if it's always the same).

**Comment by cgrdn** [comment]
**All Argo oxygen data should be in units of umol kg-1**. I trust that they all are because they are meant to be and I don't think anything else would it make it onto the GDAC (although if someone made a mistake and did umol/L, I suppose that would probably slip past). 

The unit field for the variable in the netcdf file, I imagine, is much less reliable, as it seems you've already experienced. But there shouldn't be any per volume or different molar measurements (i.e. mmol or mol etc). 

On a somewhat related note existing code for converting between oxygen quantities is a bit of a rabbit hole to jump down, as @richardsc and I have been discussing this week.

**Comment by dankelley** [comment]
Although @j-harbin was assigned this, I am going to go ahead and close it, because I was the one who posed the question.  Now that we know, this can be closed.  (Keeping it open was just a reminder that maybe we ought not to assume a unit when labelling an oxygen axis.)
