### ISSUE TITLE
PROPOSAL: getIndex() should handle 'core' as a nickname

### ISSUE THREAD

**Issue by j-harbin** [ArgoCanada/argoFloats#267]
Right now when we specify the `filename` for `getIndex()`, we have the option of doing `argo`, for core data, `bgc` or `bgcargo` for bgc, and `synthetic` for synthetic. I was just writing code and did `getIndex(filename='core')`, which to my surprise was not an option and instead its "argo". This tells me we should add this in as an option for downloading core data

**Comment by dankelley** [comment]
Good catch!  I think our code should accept `"argo"` for a while (maybe until Dec 1) but the docs should say `"core"` instead, and it should give a warning if `"argo"` is given (but still accept `"argo"`).  And then on that specified date, it will still detect `"argo"` but will make an error message saying to use `"core"` instead.

If you agree, please go ahead and do it, and make a bunch of tests in the test suite.  The docs should also contain a clear note on the change, when we made it, when the transition to error will occur, etc.

PS. since it's the default, I don't think we will be altering the functionality of anybody's code.  When I call functions, I very seldom specify default arguments, because I like short code.  Thus, I would always write `getIndex()` or `getIndex(age=SOMETHING)` but never `getIndex(filename=SOMETHING)`.  But that's just moi.

**Comment by j-harbin** [comment]
this is done in commit 939feb4815f50c644ebad871cfaf2b2ad6801aef of the develop branch. Thanks for the feedback, Dan. I will now close this issue.

**Comment by dankelley** [comment]
The warning message says as below, but `getIndex()` is not a generic method, so instead it should just be a normal message, without the `call` argument.  When you do that, it will automatically state the function that it's in.  Please fix this, and also the test (if you have one) that checks for the warning text.

**Comment by j-harbin** [comment]
Tweaks made in commit ed9bf20f2fb2ff6fa71734e2b5aeb171257a118c of the develop branch. I am now closing this issue.
