### ISSUE TITLE
Hard to see path arrow in mapApp()

### ISSUE THREAD

**Issue by j-harbin** [ArgoCanada/argoFloats#276]
As @richardsc pointed out in his comments for the paper, when using `mapApp()` and following the path  for float 6901181, it is difficult to see the path arrow that indicates direction.

![Screen Shot 2020-10-27 at 7 47 57 AM](https://user-images.githubusercontent.com/58750538/97291720-0d40ac00-1829-11eb-9610-6bfbdcd5ca99.png)

Some options I thought of to help this problem would be:
1. Change the colour of the arrow
2. Increase the size of the arrow
3. Have "start" written at the beginning of the path and "End" at the end (like I believe we initially had)
4. Have a vector next to (not on top of)  the Argo floats indicating direction

**Comment by dankelley** [comment]
What `oce::plot,section-method` does is to draw a box around the first point.  For consistency, argoFloats should mark the first, not the last point.

This will look quite nice in views that show say a month of data for multiple floats: with line segments going away from the box.

The arrow idea is not visible for a long trajectory of a single float, although it's nice when looking at a set of floats for a short time.

Colourizing the start or end will not work because the user will often want to colourize for some other reason.

Writing e.g. "S" and "E" is wildly ugly for the multi-float case, and even for the single-float case, the path can be wiggly, so often those letters get overdrawn.

That's why I think the solution is to put a symbol on the first point.  I'll do that within a half hour (break in grading).

**Comment by j-harbin** [comment]
This was discussed in a vftf with @richardsc and @dankelley. We agree that we can now see the updated "End" point in `mapApp()`. I am therefore closing this issue.
