### ISSUE TITLE
mapApp() not showing final date correctly in single-float view

### ISSUE THREAD

**Issue by dankelley** [ArgoCanada/argoFloats#279]
The pic shows (date in info box vs 'end' box) seem to disagree.  I may not be pointing a the very end, though.  No time to check for a few hours but I'll fix the problem (if it is a problem) this aft.

<img width="1022" alt="Screen Shot 2020-10-28 at 10 18 24 AM" src="https://user-images.githubusercontent.com/99469/97441047-07b99380-1907-11eb-877c-d48f2675ecdf.png">

**Comment by dankelley** [comment]
I zoomed in so I could be sure the mouse was over the point.  It is definitely a problem.

<img width="1022" alt="Screen Shot 2020-10-28 at 10 20 46 AM" src="https://user-images.githubusercontent.com/99469/97441255-48191180-1907-11eb-850d-58b8cfa83315.png">

**Comment by j-harbin** [comment]
I am confused if this issue is resolved. Based on my screenshot below, my most recent cycle (indicated by the black rectangle) was cycle 454 on 2020-08-05. You'll notice, however, that my "End" date is 2020-08-07, which aligns with Dan's screenshot that cycle 455 was taken on 2020-08-07. This is telling me for some reason, my path or trajectory does not show the last cycle, but the "End" time shows up correctly with the most recent time.

Again, no rush on this, I just happen to be on a roll with issues.

![Screen Shot 2020-11-03 at 4 14 31 PM](https://user-images.githubusercontent.com/58750538/98036113-dbfb4980-1def-11eb-95b9-39b2712adae1.png)

**Comment by dankelley** [comment]
I think you must have zoomed on it.  I think then the 'end' is the most recent point as shown, which might not be the most recent point acquired, depending on where on the trajectory you zoomed.

When I launch it, enter that float ID, and click to see the end point, I get like below.

I'm not too sure what I'm looking for, though.

<img width="1022" alt="Screen Shot 2020-11-03 at 4 25 59 PM" src="https://user-images.githubusercontent.com/99469/98036995-4fea2180-1df1-11eb-8b25-e4c5ccd7f56f.png">

**Comment by dankelley** [comment]
I think I misread the Q. I advise using `age=0` in getting the index.  Maybe (even though the profiles are old) they are updated since your last download.  When I zoom in, I get as shown below, so one more dot.

The odd thing is that the dots are only 2 days apart.

<img width="1022" alt="Screen Shot 2020-11-03 at 4 32 24 PM" src="https://user-images.githubusercontent.com/99469/98037591-2da4d380-1df2-11eb-9a85-eb482238866c.png">

**Comment by j-harbin** [comment]
This is very interesting. As per the title, this issue has been addressed. However, I am unable to reproduce your plot, and my trajectory lacks the last cycle (even with `age=0`). This could be a tomorrow problem!

**Comment by dankelley** [comment]
All good (Z)
