### ISSUE TITLE
summary plot doesn't work for cycles with multiple profiles

### ISSUE THREAD

**Issue by j-harbin** [ArgoCanada/argoFloats#298]
This is shown in the following code:

```R
library(argoFloats)
index1 <- subset(getIndex(), circle=list(latitude=12.25, longitude=64.33, radius=40))
argos <- readProfiles(getProfiles(index1))
plot(argos, which="summary",
     summaryControl=list(items=c("dataStateIndicator","length","longitude","latitude")))
```

receiving the following error:

```R
Error in xy.coords(x, y, xlabel, ylabel, log) : 
  'list' object cannot be coerced to type 'double'
```

**Comment by dankelley** [comment]
I think this is because of cycles that have multiple profiles within them.  I'll look into it.

**Comment by dankelley** [comment]
Fixed in "develop" branch.  As a test, try running `issues/2xx/298/issue298.R` (which I made based on your demo code).

**Comment by dankelley** [comment]
The problem was with lon and lat.  Now, I just take the first value of each, in case there are multiple values.  I think they are likely always the same anyway, since there is only one satellite fix.  I've not checked that.  

If @j-harbin has time, it might make sense to check my idea, starting with the code I name in my previous comment. But my understanding of the netcdf files is just that the extra profiles are contained as multiple columns, but that time is a single value.  Hm.  @j-harbin this might be good for you to check. 

PS. As a reminder, the code I was using to easily browse netcdf files was `ncdump`, which comes from inside `netcdf`, a system installed with `homebrew`. I am in love with `homebrew`, but it can be handy. Whether I recommend it, I'm not too sure.  I think it's a good way to wreck your OS -- not usually considered to be AGT (a good thing).
