### ISSUE TITLE
Subset by cycle not working properly

### ISSUE THREAD

**Issue by j-harbin** [ArgoCanada/argoFloats#302]
I was actually working on something else when I came across this bug:

```R
library(argoFloats)
data("index")
index1 <- subset(index, cycle=c(080,086))
index1[["cycle"]]
```
produces:

```R
[1] "086" "186" "080" "086" "186" "186"
 [7] "086" "180" "180" "180" "280" "186"
[13] "080" "086" "080" "086"
```
ie. when I type, for example, `cycle=080` it is picking up `180` and `280` as well. And when I type `cycle=086` it is picking up `186` as well.

**Comment by dankelley** [comment]
You have to give `cycle` as a character value.  R converts 080 into 80 because it's a number. Then we are doing a grep on whether 180 and 280 (as strings) contain 80, and of course they do.

I think there should be a test in `subset()` that does `is.character(cycle)` and, if not, then spits an error.  And the docs on subset should do that.  And all sample code should do that.  Using `git grep` is a great way to find all problem cases.

**Comment by j-harbin** [comment]
Done in commit bcdb7c9469e5d34d5c0671f54edc8b15a99f049f of the develop branch.
