### ISSUE TITLE
Add colLand arg to mapApp()

### ISSUE THREAD

**Issue by j-harbin** [ArgoCanada/argoFloats#330]

**Comment by j-harbin** [comment]
Just using this as a place to make notes for myself (and avoiding little sticky notes all over my office)!

Currently, for `oce`:
1. for e.g.,`plot(argo, col="blue")`, the `col` argument changes the colour of the Argo profiling floats
2. for e.g., `mapPlot(coastlineWorld, col="red")` or `mapPolygon()`, the `col` argument changes the colour of the land. 

For `argoFloats`
1. For e.g., `plot(index, col="red")`, `col` changes the colour of the Argo profiling floats (ie. analogous to example one of `oce`.

**Comment by dankelley** [comment]
It should not be called `col` because then is it the colour of the dots, the colour of the land, the colour of the coastline, the colour of a profile, etc.

We have a convention of splitting args into special purposes so the colour should go into `mapControl`.  See the other code for hints.  And I think it has to be called `colLand` so we can have other `colSOMETHING` items.

**Comment by j-harbin** [comment]
Done in commit 7c3fc4443c153cb01af84cb9e0363b43b8533848 of the develop branch.

**Comment by dankelley** [comment]
@j-harbin, mind if I reopen this?  It would be great if the `server` arg would be the same as in `getIndex()`.  As the snapshot shows, this is not the case.  (Users benefit from uniformity.)

Also, the `mapApp()` order of `destdir` and `server` ought to be the same as for `getIndex()`.

I know I'm "to blame" for the order, etc., since I wrote `mapApp()`, but it would be great if you could fix this.
<img width="874" alt="Screen Shot 2020-12-14 at 8 31 33 AM" src="https://user-images.githubusercontent.com/99469/102081690-04129b00-3de7-11eb-98b5-3e0035852b66.png">

**Comment by j-harbin** [comment]
Fixed in commit 611656fda50e9140b77028df7bd1e60b5eccbab2 of the develop branch. Feel free to request any other changes you see fit :)

**Comment by dankelley** [comment]
Thanks. I just pushed a commit that uses a roxygen template for the `server` parameter.  The advantage of that is that it can be referred to in the docs for other functions.  Then, if something changes (or we just want to reword for clarity), all the functions get the improvements.

Maybe you can check that it still builds ok for you, and close the issue if you (as I) think it's been addressed successfully.

**Comment by j-harbin** [comment]
Done!
