### ISSUE TITLE
Colour-code path projections with core, BGC, and deep in mapApp()

### ISSUE THREAD

**Issue by j-harbin** [ArgoCanada/argoFloats#343]
Currently all paths show up as black. I will make it such that core is displayed in black, BGC in green, and deep in purple

**Comment by dankelley** [comment]
I was wondering whether we ought to have an option to let users control things like line colour, line width, symbol type, symbol colour, symbol size, etc.  This might be quite "busy" but it could be hidden in a tab called "settings".

Why would this be nice?  Well, because people might want to use the app to make graphs for talks, etc.  Of course, they could always hit "code" and then tweak that code, so I am not too sure that I think this is required.  The only thing is ... in playing around lately (mostly looking at trajectories, not at points) I find myself wanting to do things like set a colour with an "alpha" level, but I sort of don't want to go into writing argoFloats code, and would prefer to have the app do it.

Any thoughts on this, @j-harbin?

**Comment by j-harbin** [comment]
I hadn't thought of the idea of a "Settings" tab before! I like that a lot. I would suggest by default having the path colour correspond to the Argo float type, but then I could add a "Settings" tab to have the option to change the variables you stated above?

Thoughts?

**Comment by dankelley** [comment]
Yes, I like this.  Users are familiar with 'Settings' in applications.  We could also move those buttons for showing core, etc., to settings.

**Comment by j-harbin** [comment]
Done in commit afa059d146999fac8eb15314f11804edd53cab8c of the develop branch. I will create a new issue for the creation of a settings tab.
