### ISSUE TITLE
Should showQCTests test to make sure data is "realtime"?

### ISSUE THREAD

**Issue by j-harbin** [ArgoCanada/argoFloats#353]
Based on recent information from DMQC specialists, it seems that HISTORY_QCTEST (which we use for `showQCTests()`) only reveals tests for real-time floats before having QC done by hand in delayed mode. I think we should have a test that makes sure only real-time data works for `showQCTests` and in the meantime, determine where delayed mode test information is stored.

Thoughts?

**Comment by dankelley** [comment]
This makes sense, although I'm not sure what the test would be, actually.

One important thing -- I think, the *most* important -- would be to document our suspicion (or finding, if Chris Gordon has a citation on this) about this hexcode being just for realtime.  We used a lot of time on this, and we ought to let users know what's going on, in our docs.  It will only take a few words, and it could save users a lot of time.

Frankly, I think the hex string is of very little value, and I'd like to see the word "Caution" in bold-face within our docs.

My guess is that the delayed-mode test information is not stored anywhere.  In this one test case, we sort of see something, awkwardly phrased, in what is probably a hand-written comment.  Hand-written comments are not of much value, because they cannot be interpreted in code.  I might say "the third point is questionable" but another part of my comment might need to be understood to know that I mean third from the bottom.  Or I might say "funky" instead of "questionable".  Etc and so on ... hand-written comments *can* be useful, but lots of time they are not.  It's like git commit notes: some bad people (looking at myself in my laptop screen) use "." as the commit note, half the time!

**Comment by j-harbin** [comment]
Docs have been updated for `showQCTests` in commit d56c24c63c8d5051ee9872afef8b385f3faf7ac0 of the develop branch.

**Comment by dankelley** [comment]
Please see the comment I made in the commit.
