### ISSUE TITLE
mapApp() not showing end-time box

### ISSUE THREAD

**Issue by dankelley** [ArgoCanada/argoFloats#384]
See snapshot.

<img width="878" alt="Screen Shot 2021-02-08 at 11 30 15 AM" src="https://user-images.githubusercontent.com/99469/107241166-1b45c180-6a01-11eb-88c3-f52ebacc15fd.png">

**Comment by j-harbin** [comment]
Good catch on this, Dan. It seems in commit 29da759761983946eee233a11817564f45cb87cd of the develop branch, when I was making it such that the widgets showed up after we got the index, I forgot to add the "End" widget back.

This is fixed in commit cc016c01085c4b2b154749ab36844fcca6144845 of the develop branch. Feel free to close this issue if you see fit.

**Comment by dankelley** [comment]
Thanks.  I also widened the end-time by 1 em-space, because it was cut off on my machine.  ("develop" commit 33f8a3d2adec8897361dfd6a0ece73bc67b8a455)
