### ISSUE TITLE
Creating an argoFloats logo

### ISSUE THREAD

**Issue by j-harbin** [ArgoCanada/argoFloats#39]
Hi Team,

I've created a draft of a logo for the argoFloats package. Any feedback is greatly appreciated. It was good to get familiar with the `hexSticker` package.

The code for the the logo can be found under https://github.com/dankelley/argoFloats/blob/develop/sandbox/jlh/02_Logo/01_Logo.R

The *rough* logo is below:
![argoFloatsLogo](https://user-images.githubusercontent.com/58750538/77341305-4a7e1200-6d0d-11ea-8e91-6d96fe5b0be9.png)

**Comment by dankelley** [comment]
@richardsc and @j-harbin: I propose that we edit this comment *in-place* as a repository of stickers that we can compare.  Let's add new ones at the bottom, and let's refer to them as 1 for the first, 2 for the second, and so forth. Eventually, we can vote.

https://github.com/dankelley/argoFloats/blob/develop/sandbox/jlh/02_Logo/01_Logo.R
![77341305-4a7e1200-6d0d-11ea-8e91-6d96fe5b0be9](https://user-images.githubusercontent.com/99469/81583196-5db17380-9387-11ea-88ef-329306fdaa7c.png)

https://github.com/ArgoCanada/argoFloats/blob/develop/sandbox/dek/05_hex_logo/argoFloats_logo_02.R
![argoFloats_logo_02](https://user-images.githubusercontent.com/99469/81583127-470b1c80-9387-11ea-912c-227777f22911.png)

https://github.com/ArgoCanada/argoFloats/blob/develop/sandbox/dek/05_hex_logo/argoFloats_logo_03.R
![argoFloats_logo_03](https://user-images.githubusercontent.com/99469/81583133-48d4e000-9387-11ea-9756-5d8fb0851287.png)

**Comment by richardsc** [comment]
I think my current favourite is the 3rd one, though I would argue for removing the "R" from the title.

Also, what if we removed the numbers on the axes (I know that it wouldn't be a "proper" map then, but the point is just to show a somewhat-recognizable map, not a publication-quality figure)?

**Comment by j-harbin** [comment]
I agree, number three is definitely my favourite and two very good points brought up by Clark. 

I'd be interested in seeing number three, with Clark's recommendations, then with a more neutral background (ie. black or white), and the boarder being the same colour as the text of `argoFloats`. 

I think it could look quite sharp, but also don't mind the yellow background as well. The suggestion of change in colour is more of a curiosity sake for me.

**Comment by dankelley** [comment]
I like the R because then people know it's an R thing, not a python thing or a matlab thing.  What's the reason to remove it?

I like the numbers because I think this is a pretty neat spot, with deep water right up beside an island, and I want people to learn about the spot.  (The more I plot bathymetry, etc., the more excited I get about this spot. It is unusual for me to care a spot in this way.  I'm the guy who thinks its stupid to even know the names of oceans.)

**Comment by dankelley** [comment]
@j-harbin if you want to try with no numbers, that might be good, so we aren't just imagining.  You need to change 4 things in the code (width, height, x offset, y offset) in argoFloats/sandbox/dek/05_hex_logo ... it takes some fiddling to get things looking nice, but I'd say what we want is to enlarge the graph as much as possible without hitting other things, or getting so close that it looks ugly.

**Comment by richardsc** [comment]
As for why remove the R: hex stickers *ARE* and R thing (say that 5 times fast). To my knowledge they are not used for other package systems, so the "R" is redundant.

Check out all the examples in the README [here](https://github.com/GuangchuangYu/hexSticker), e.g.
![image](https://user-images.githubusercontent.com/233584/82069239-64065f00-96a9-11ea-9107-2a14c7467f76.png)

**Comment by dankelley** [comment]
Good point.  So, I'll remove the R, unless @j-harbin objects...

**Comment by richardsc** [comment]
As for the map, I understand the desire to know where it is. One solution to that is to somehow include the hexsticker code in the repository (or in the README?) so that an interested user can find out easily.

**Comment by dankelley** [comment]
The code is too long and complicated for the README.  It's in the repo, of course (and so is the topo file, without which it won't work).

**Comment by j-harbin** [comment]
Hi Team,

Logo 04 https://github.com/ArgoCanada/argoFloats/blob/develop/sandbox/jlh/02_Logo/04_logo.R
Removed the 'R' in the title, changed the background to white, and changed the border colour

![Screen Shot 2020-05-25 at 8 35 41 AM](https://user-images.githubusercontent.com/58750538/82809682-0d481480-9e63-11ea-9f05-09a19677e0cb.png)

Logo 05 https://github.com/ArgoCanada/argoFloats/blob/develop/sandbox/jlh/02_Logo/05_logo.R
Removed the 'R' in the title, and changed the border colour

![Screen Shot 2020-05-25 at 8 34 51 AM](https://user-images.githubusercontent.com/58750538/82809689-133df580-9e63-11ea-966e-e2ab549385c5.png)

Logo 06 https://github.com/ArgoCanada/argoFloats/blob/develop/sandbox/jlh/02_Logo/06_logo.R
Removed the 'R' in the title, changed the border colour, and removed the axes

![Screen Shot 2020-05-25 at 8 41 47 AM](https://user-images.githubusercontent.com/58750538/82809932-9e1ef000-9e63-11ea-8175-920290f6f2db.png)


Please ignore the black background behind the logos, it is simply the setting of my laptop. I personally am not in favour of the white background in logo 04. I do, however, like logos 05 and 06, with 05 being the favourite with the axes included.

Thoughts?

**Comment by dankelley** [comment]
This is funny -- @j-harbin and I must have been updating the logo at the exact same time!  I also put two new updates at https://github.com/ArgoCanada/argoFloats/issues/39#issuecomment-626795267

J's 6 and my 5 are quite similar.

It would be sweet if they were all in one comment.  @j-harbin can you put them into https://github.com/ArgoCanada/argoFloats/issues/39#issuecomment-626795267 with titles "JH (number)" etc?  Once you're done, I'll change the titles of the ones I did to "DK (number)".  That way we should be able to refer to them without too much confusion. Having them all in one comment will make it easier to judge.

**Comment by j-harbin** [comment]
That is quite funny. I just updated mine into #39 (comment).  I like DK 4 with a purple border and no 'R' in the title. Thoughts?

**Comment by j-harbin** [comment]
@dankelley, we are on the same wavelength today. I just went to update the comment to include our new logo created in our vftf and saw you already did it. As discussed, it may be a good idea for everyone to have any variation of the logo they may want in by this Friday. We can then take a vote of our top 3 to decide on one.

**Comment by dankelley** [comment]
I propose we send in our ranked top 3 votes to @j-harbin, who can tabulate them and make the decision. That way, we don't get into the problem of open votes (mode 1: "me to" rather than look; mode 2: "why vote now, I'm outvoted anyhow"; etc)

**Comment by dankelley** [comment]
@j-harbin, maybe you could merge the votes, and state the decision here.  Once we have that, maybe you can make a top-level directory called "logo" (and put `^logo$` in `.Rbuildignore`), and put the final code there.  (Right now, the code is buried in one sandbox or another, and it's too much to ask users to try to figure out which one.)  Thanks, team!

**Comment by j-harbin** [comment]
Thank you all for the votes. The winner is DK 6 (with JH) (shown below). The code can be found at   https://github.com/ArgoCanada/argoFloats/blob/develop/logo/logo.R, and was completed in commit a9cc0709026c0c581a99a5c4ed89cb024412ee1d of the develop branch.

**Comment by dankelley** [comment]
FYI, I added the topo file to the repo, with
```
git add -f topo_81W_72W_22N_31N_1min_gmt.nc
```
where the `-f` is needed because our `.gitignore` is set up to ignore such files.

Oh, and I also added the resultant `.png`, because people might like to see it, and it's a bit of a hassle to build this file, unless the user installs the `argoFloats`, `cmocean` and `hexSticker` packages.

**Comment by dankelley** [comment]
I like the map but the diagram is confusing.  Is the code in a sandbox?  (It might be nice to put the sandbox filename beside each plot, so we can keep track, and make variants.)

**Comment by j-harbin** [comment]
Thanks to the stale bot for reminding me of this issue. Dan, I agree that there was too much going on with the TS diagram. I made a simpler version that I quite like. I know you're busy with other work right now, so there is no rush for comments on this. All code can be found in argoFloats/sandbox/jlh/40_hexsticker
![argoTag_hex_sticker2](https://user-images.githubusercontent.com/58750538/205302545-607a899a-f986-4ad2-829b-02c9edc64a94.png)

**Comment by dankelley** [comment]
One thing -- find a way to view it at 4 cm width, since that's the size of the argoTag sticker.  (It will also be the size of any new oce stickers I make ... the present ones are big because I didn't look at the size it was suggesting by default!)

You know me ... I always like large fonts in anything.  Therefore, I'd try to use up more of that land space for the title.

Colours:
1. The blue looks a lot like black to me, so maybe brighten it?
2. The black border seems a bit strong.  I might suggest something not quite so black.
3. The word is also full-black.  Maybe make the border and it both be different shades of gray, if you like to stay in the blackish theme. 
4. I might alter the depth colour palette a bit to get some darker colours (but not so dark as to hide the float positions of course).

These little fiddles can be hard to decide on.  I'm not too sure if I feel strongly about any of these suggestions, actually.

**Comment by j-harbin** [comment]
I made your suggestions. I'll admit I wasn't sure how to ensure the 4 cm size was correct, so I just copied the height, width, and resolution that we did for the `argoTag` sticker. Furthermore, I changed the Pacific positions to be green instead of blue. Lastly, the "argoFloats" title is not centred with the land, but it is centred with the sticker itself. 

![argoTag_hex_sticker2](https://user-images.githubusercontent.com/58750538/205310297-3dc4da09-9bd5-47a4-8910-40f1516307d7.png)

**Comment by dankelley** [comment]
I'm a bit lost, actually.  I pulled the repo ("develop" branch) but when I build your file `argoFloats/sandbox/jlh/40_hexsticker/hex_sticker_03.R` I get as below.  Maybe you're on another branch?  (Or maybe I have the file wrong?)

We might benefit from a quick Z to settle this.

**Comment by dankelley** [comment]
I made a variant, shown below.  To recreate it, do
```
cd sandbox/dek/05_hex_logo
make
```
The first time you do this, it may take a minute because it downloads an argo index, does subsetting, etc.  But after that it takes maybe 10 seconds to run, which is advantageous in terms of fiddling with colours.

And I did fiddle with colours a bit, and sizes, etc.  I think it may be clearer now, because the logo name is now darker and I made the land lighter.

The way to see if this looks good is to load the png in Preview (if on a mac) and resize it until it is the width of a sticker.  I think we all have the argoTags sticker on our computer (maybe!), so that makes it easy.

I also cleaned up the code. There were remnants from old attempts in there.  This involved removing unused variables, renaming variables, etc. This may make it easier for someone (maybe us) to understand the code.

![argoFloats_hex_dk_07](https://user-images.githubusercontent.com/99469/205440233-a47919e3-7fb3-4988-bebe-480869ba8d75.png)

**Comment by j-harbin** [comment]
@dankelley, I like the above sticker. I think this issue can be considered complete. What do you think?

**Comment by dankelley** [comment]
I agree that it's complete.  I propose to order some, after the holiday, so let's leave the issue open until then.  @j-harbin what amount should I order and what size?  I propose to order 50 or so (I think they have deals at certain counts) and to use the smaller size, like we have for argoTags, because the ones I made for oce are really quite big.

**Comment by j-harbin** [comment]
I agree! The argoTag stickers are the perfect size.... and they are just so cute!

**Comment by j-harbin** [comment]
@dankelley, where does this stand? Did we ever order these?

**Comment by dankelley** [comment]
I don't have one on my laptop, so I think not.  If you like the one shown below, I can order some today.  I have to figure out what that small size was we used for argoTags, since the size I used for oce was bigger than I wanted.


![](https://user-images.githubusercontent.com/99469/205440233-a47919e3-7fb3-4988-bebe-480869ba8d75.png)

**Comment by j-harbin** [comment]
+1 for the sticker above with the `argoTag` size.

**Comment by dankelley** [comment]
Stickers ordered.
