### ISSUE TITLE
plot(..., which="map") appears to have a doubled coastline

### ISSUE THREAD

**Issue by richardsc** [ArgoCanada/argoFloats#399]
See reprex, and look closely at the coastline. It looks like it's being plotted twice, at two different resolutions. (Also, check out this particular float, which has an interesting story)

``` r
library(argoFloats)
index <- getIndex()
si <- subset(index, ID=4902426)
#> Kept 389 profiles (0.0161%)
plot(si, which="map")
```

![](https://i.imgur.com/WTtBySB.png)

<sup>Created on 2021-02-14 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by j-harbin** [comment]
Good catch on this, Clark. This was a result of when I added in the `colLand` argument, I was drawing the `coastlineWorldFine` over everything. This was fixed in commit db60a7ff83540ea35add38b75b30d968c2bba904 of the develop branch. The new image is shown below.

![Screen Shot 2021-02-17 at 9 29 48 AM](https://user-images.githubusercontent.com/58750538/108211105-b413c580-7102-11eb-9d0f-e95d502a3908.png)

I know you're busy, so I will close this, but of course feel free to re-open if you see any further problems.
