### ISSUE TITLE
mapApp() should have a an "End" date option

### ISSUE THREAD

**Issue by richardsc** [ArgoCanada/argoFloats#404]
Given that you can choose a "Start" date, I'm curious why mapApp() doesn't allow you to choose the "End" date for a subset -- rather it appears to default to end on whatever is the latest date in the index. An example use case would be if I only want to view floats within a given time range, say 2018-01-01 to 2019-01-01.

**Comment by j-harbin** [comment]
Are you working on the most up-to-date version of `mapApp()`? The reason I ask is because at one point I accidentally deleted the "End" date for subset. This was noticed by Dan (https://github.com/ArgoCanada/argoFloats/issues/384) and was fixed in commit cc016c0 of the develop branch a few weeks back.

The current `mapApp()` interface looks like this.

![Screen Shot 2021-02-19 at 7 10 25 AM](https://user-images.githubusercontent.com/58750538/108497485-e435a280-7281-11eb-8c13-9909cc7c435a.png)

Note that the user has the ability to click on "Start" or "End" and to choose their own date:

![Screen Shot 2021-02-19 at 7 15 28 AM](https://user-images.githubusercontent.com/58750538/108497710-4393b280-7282-11eb-9d1a-2e58ddc6911d.png)

**Comment by richardsc** [comment]
Oh shoot. I was afraid I was just missing something. I *thought* I was working from the latest version, but I think what happened was that I have it installed on my machine twice (once in Windows and once in the Windows Linux Subsystem) and I used the older one ...

Ooops!

**Comment by dankelley** [comment]
https://www.youtube.com/watch?v=VC3thojIrFc
