### ISSUE TITLE
PROPOSAL: Set flag =0 to be considered "good" data for applyQC

### ISSUE THREAD

**Issue by j-harbin** [ArgoCanada/argoFloats#434]
Currently `applyQC()` treats flags 0,3,4,6,7, and 9 as "bad" data. A flag of 0 is "not accessed". This could be problematic as shown in https://github.com/ArgoCanada/argoFloats/issues/433 for example, which suggests all data are bad, but when I inspected the flags, they're just either NA or 0. Note: this example is currently only reproducible in branch issue421.

<details>

``` r
library(argoFloats)
ai <- getIndex("traj")
index1 <- subset(ai, ID='1902221')
#> Kept 1 trajectories (0.0057%)
argos <- readProfiles(getProfiles(index1))
#> Warning in FUN(X[[i]], ...): This file has no STATION_PARAMETERS item, so an
#> attempt is made to discover some important fields for inclusion in the data slot
#> of the return value. However, other variabiles will go in the metadata slot, so
#> be aware of this problem during further processing.
#> Warning in readProfiles(getProfiles(index1)): Of 1 profiles read, 1 has >10% of pressure values with QC flag of 4, signalling bad data.
#>     The indices of the bad profiles are as follows.
#>     1
#> Warning in readProfiles(getProfiles(index1)): Of 1 profiles read, 1 has >10% of salinity values with QC flag of 4, signalling bad data.
#>     The indices of the bad profiles are as follows.
#>     1
#> Warning in readProfiles(getProfiles(index1)): Of 1 profiles read, 1 has >10% of temperature values with QC flag of 4, signalling bad data.
#>     The indices of the bad profiles are as follows.
#>     1
plot(argos, which="TS")
```

![](https://i.imgur.com/pcX8Vmj.png)

<sup>Created on 2021-04-09 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by dankelley** [comment]
I wondered about that, too.  My guess is that trajectory files are simply not assessed.  But how do we colour them?  Do we guess good or guess bad?

I wonder if we ought to have a three-colour scheme:
* black if "good"
* amber (or something like that) if not assessed
* red if (in some way) bad

This is a bit like traffic lights, except that the default is black instead of green.  (I think black is the natural default for graphs.)

Your thoughts, @j-harbin and @richardsc?

**Comment by j-harbin** [comment]
Oh, I quite like that idea. If we take that approach, I vote flags 0 (not assessed), and 9 (missing value) should be amber.

**Comment by dankelley** [comment]
+1 on your vote that 0 and 9 are amber.  Let's talk about colours. How about (as below) col=1 for OK, col=2 (like red) for bad, and col=7 (like amber) for questionable.

One thing that's confusing is that in `mapApp()`, we use amber for "core" positions.  That's because otherwise positions can look like islands.  But I don't really want to get too bound up in consistency, e.g. I like the green hues we use i `mapApp()` for bgc, where it means something related to life (green for plants), and I don't see that as confusing.

Another option, which I also quite like, is to use gray (8 below) for not-yet-assessed data.

Actually, now that I type this, I think I prefer gray for flag=0 etc.

Discussion on GH is tricky in such weighing of options.

``` r
n <- 8
col <- palette.colors(n, "R4")
plot(1:n, 1:n, pch=20, col=col, cex=3)
```

![](https://i.imgur.com/aoyA7vC.png)

<sup>Created on 2021-04-09 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by richardsc** [comment]
I like grey for "not assessed".

And @dankelley is right -- for the most part the data contained in traj files is not run through RT or DMQC (we were talking about it at Argo Canada recently, though).

**Comment by j-harbin** [comment]
Ok. I like the 3-colour scheme. However, when we have something like the following:

```R
library(argoFloats)
data("index")
index1 <- subset(index, ID=1901584)
argos <- readProfiles(getProfiles(index1))
clean <- applyQC(argos)
```

Would flags 0 and 9 show up in the "clean" data?

**Comment by richardsc** [comment]
My opinion is that “not assessed” should *not* show up after a default call of `applyQC()`.

**Comment by dankelley** [comment]
I agree with Clark on this; `applyQC()` should set unchecked data to `NAusing an `. For one thing, `applyQC()` is documented as using an `oce` function to handle the flags.  And therefore, we ought to do what `oce` does (and has done, for years ... users have a right to expect `oce` not to change unless there is a very, very good reason, and then only slowly, with notice of an upcoming change, etc.).

To my mind, colours on a plot are quite a different thing than the output of `applyQC()`.

I think that plot should show gray dots if the flag is 0.  By eye, then, such plots will show black for things we can trust, gray for things that might be okay or might be bad, and red for things that are judged to be bad.

**Comment by j-harbin** [comment]
Flags that are 0 (ie. not accessed) now plot gray on the TS plot and the documentation has been updated. This was completed commit ca1a6a0371d16d5549191263345baa03911fcf4a in of the develop branch. See reprex below.

``` r
library(argoFloats)
ai <- getIndex("traj")
index1 <- subset(ai, ID='1902221')
#> Kept 1 trajectories (0.0057%)
argos <- readProfiles(getProfiles(index1))
#> Warning in oce::read.argo(fullFileNames[i], debug = debug - 1): This file has no
#> STATION_PARAMETERS item, so an attempt is made to discover some important fields
#> for inclusion in the data slot of the return value. However, other variabiles
#> will go in the metadata slot, so be aware of this problem during further
#> processing.
#> Warning in readProfiles(getProfiles(index1)): Of 1 profiles read, 1 has >10% of pressure values with QC flag of 4, signalling bad data.
#>     The indices of the bad profiles are as follows.
#>     1
#> Warning in readProfiles(getProfiles(index1)): Of 1 profiles read, 1 has >10% of salinity values with QC flag of 4, signalling bad data.
#>     The indices of the bad profiles are as follows.
#>     1
#> Warning in readProfiles(getProfiles(index1)): Of 1 profiles read, 1 has >10% of temperature values with QC flag of 4, signalling bad data.
#>     The indices of the bad profiles are as follows.
#>     1
plot(argos, which="TS")
```

![](https://i.imgur.com/DyBsA9j.png)

<sup>Created on 2021-04-14 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
