### ISSUE TITLE
mapApp() "Settings" tab not formatted properly initially

### ISSUE THREAD

**Issue by j-harbin** [ArgoCanada/argoFloats#476]
As shown in the screen shot below, when mapApp() initially loads up, the settings tab format is not good. However, in the second screen shot you see that when I extend out the mapApp() tab (clicking and dragging the border of mapApp()), it looks fine).

![Screen Shot 2021-08-09 at 1 26 17 PM](https://user-images.githubusercontent.com/58750538/128740374-b39f5a42-3686-42d5-be04-4ce037862647.png)

![Screen Shot 2021-08-09 at 1 26 26 PM](https://user-images.githubusercontent.com/58750538/128740370-81d3731e-bc8b-44b5-9862-023c36c8e3a9.png)

**Comment by dankelley** [comment]
I'm not sure I follow this.  @j-harbin, did you put your screenshots in the wrong order?  I get the something like second of your screenshots when I load up `mapApp()`.  And it doesn't really change when I alter the window size.

Maybe it's different on different machines?

Also, I'm not too sure what you mean by not being formatted properly.

It might help to Z about this, since it's one of 3 issues holding up a CRAN submission.

**Comment by dankelley** [comment]
During a f2f, J and I agree to close this, because it doesn't appear on my computer.  I think it's just one of those things that happens in web browsers, generally, and so it's not a problem with our code.
