### ISSUE TITLE
Double click operation not always working properly

### ISSUE THREAD

**Issue by j-harbin** [ArgoCanada/argoFloats#504]
Note that beginning of this discussion started in https://github.com/ArgoCanada/argoFloats/issues/503 . Initially, I thought that the problem only occurred when "path" was selected, and that is not true. 

**Sometimes** (not always) if I just load `mapApp()` and double click a float I get the photo below (ie. no floats showing). I have so far only experienced this with Deep and BGC floats and not yet with core floats, but I'm not saying it doesn't happen with core. It's also worth noting that this doesn't **always** happen, but I would say about 50% of the time for Deep and BGC. Could someone try this out to see if it's only on my end?

![Screen Shot 2021-09-22 at 11 21 57 AM](https://user-images.githubusercontent.com/58750538/134367464-1eeaf603-b869-4247-a497-8600ab79180a.png)

**Comment by dankelley** [comment]
During out f2f, we realized that the problem ocuurs when viewing a subset.  Say, for example, that only Deep is being viewed.  If a double-click occurs far from one of the float positions, mapApp will find *any* float (most likely a Core one) near that point, and centre there.  But it won't display it, because the view is restricted to Deep in this case.

The solution is not to zoom upon a double-click, *unless* a profile of the visible type is within a certain distance of the mouse.

We think the distance is 100km, regardless of the map scale.  Well, 100km makes sense for core, and for zoomed-in views, but there is some question as to whether that criterion ought to be changed for world views.  We think it is best to retain this 100km criterion (for both click and hover) because (1) that has been in existence for quite a while, (2) a user will be inspecting the hover box to see if they are near a float, and it's very easy for them to just zoom the plot if the float doesn't show up in the hover box.

@j-harbin will make the code fix.  We are aiming for a solution this week, if possible.  However, we want to get this right, and next week will be fine.  We plan for a few-day "frozen" period before a CRAN release.  Since we were thinking of a CRAN release tomorrow (2021-09-24), we will move that 1 week later, at least.

**Comment by j-harbin** [comment]
This is fixed in commit 8594824eff255899e27838c7f38db5a889a72a7e of develop. If it all seems to work out on your end feel free to close this issue!

**Comment by dankelley** [comment]
Any chance I could ask you to indent that code block?

**Comment by j-harbin** [comment]
Done

**Comment by dankelley** [comment]
Your quick -- so quick I couldn't find an xkcd cartoon about code indentation :-)

**Comment by dankelley** [comment]
Couldn't find a cartoon on code indentation, but https://xkcd.com/1732/ is worth a look in general.

**Comment by dankelley** [comment]
Looks great, thanks! 🤓
