### ISSUE TITLE
countdown to CRAN release

### ISSUE THREAD

**Issue by dankelley** [ArgoCanada/argoFloats#513]
I propose that both I and @j-harbin use `mapApp()` for a while today, to see if there are any remaining issues.  If not, then I propose to release to CRAN on Saturday.  (This timetable was discussed in a Z meeting between the two of us; the point of this issue is just to set a place for discussion.)

* [ ] Kelley finds no problems with `mapApp()` after > 1 hour of usage
* [x] Harbin finds no problems with `mapApp()` after > 1 hour of usage

**Comment by dankelley** [comment]
Sorry for the delay in looking at this -- teaching 'n such :-)

I wouldn't mind a Z sometime in the week of Oct 4, to chat about a small bit of confusion I have about the float-single/all controls.  I made a video in which I'm trying to show how a user might get confused by these.  

Whether we want to change the interface, I'm not sure.  I basically think that what we are doing is the best thing, but on the other hand, I do think it makes sense to chat about this because brainstorming is the best way to improve a UI.

https://user-images.githubusercontent.com/99469/135713957-5eb9c731-4129-4a85-942a-2d58c4d9c648.mp4

**Comment by dankelley** [comment]
One possible solution to the question in the video I just uploaded: the "Focus" popup menu might have multiple options.  A rough idea is given below.  There might be other good choices.

NOTE: I am not actually sure that "Single" means anything.  I think when we go to "All" then the float ID gets erased (which I approve of) and so there's no way for the user to know *which* single ID to look at.

My confusion on all of this is why I'd like to chat about it.  I will be busy through the week but I think 20 minutes would help.

1. Single ID (historical time range)
2. All IDs (without changing time range)
3. All IDs (last 10 days)

**Comment by j-harbin** [comment]
I worry that changing "Focus" to have a popup menu of the options you presented might make `mapApp()` a little complicated. It's funny you mention in the video that you never fully understood how you should use focus, because I would have to agree.

My question is why would a user **ever** want to go from "Single" to "All". Is it true that "All" simply just shows all of the floats in zoomed region for an arbitrary time range (ie. 10 days). If so, the use has this ability by simply zooming into a region and selecting a time range. To me "All" is not necessary. I vote we remove the "Focus" widget  entirely and simply have "Focus ID", which would then go to the "single" view. Of course I can Z on this.
