### ISSUE TITLE
add wiki item on how we handle requests for code changes

### ISSUE THREAD

**Issue by dankelley** [ArgoCanada/argoFloats#547]
@j-harbin and I talked about this today, so I'm assigning appropriately.  This might help as more people start using the package.

**Comment by j-harbin** [comment]
Thoughts on this flow diagram to determine if a suggested change should be implemented?
![Screen Shot 2022-04-04 at 10 29 34 AM](https://user-images.githubusercontent.com/58750538/161554679-fce1536a-4e5e-4fe0-8226-7e987d1f77a9.png)

**Comment by j-harbin** [comment]
Tweaks have been made to the above tree based off of DK comments in vftf. The updated figure is as follows and can be found at https://github.com/ArgoCanada/argoFloats/wiki/How-to-decide-on-a-new-functionality . I'll close this issue since Dk and I had a vftf.


![Screen Shot 2022-04-04 at 1 37 11 PM](https://user-images.githubusercontent.com/58750538/161591093-c7072505-b4c3-4a2c-a108-6213f61f0095.png)
