### ISSUE TITLE
Weird behaviour after typing in a float ID

### ISSUE THREAD

**Issue by richardsc** [ArgoCanada/argoFloats#555]
Not sure if it's reproducible yet, but I tried going from "full" view to just looking at one ID, and the app went into an oscillatory state, I think because a subset of the ID I wanted (3901851) was *also* a valid ID (39018). See screen capture below:

https://user-images.githubusercontent.com/233584/163575586-3417ad5f-0b17-4e24-9eaf-7b55e2410ef0.mov

**Comment by richardsc** [comment]
I notice that as you're typing in an ID number, the app doesn't wait for you to finish, and will pop up error messages in the bottom left telling you that it can't find float ID 1, 19, 190 etc.

**Comment by dankelley** [comment]
That flashing issue is known.  I think it's because it's responding to one event and then getting another that contradicts it.  This doesn't happen much in simple shiny systems that can redraw quickly.  I am not 100% sure on a fix, but @j-harbin is aware of the issue, and perhaps has it on the radar to be addressed.

That error message that comes as you type can be eliminated simply, by not testing.  But we do want to test when the info is complete.  Maybe if all float IDs are known to have a certain number of characters, we could use that.

Both of these could be alleviated by having a button called "update", and making it so that no updates occur until you click it.  I think the whale app does that.  Making a switch like that would alter the experience quite a lot, so it would have to be a decision made with some thought.  It might also be a lot of recoding.

Ultimately, I think these issues come down to how event handling is set up in shiny.  Some UI elements have `delay`, `debounce` and similar arguments, but not all of them do.  

Events can be tricky. For example, when you press the mouse, drag it to a new location, and then release it, this is called a "brush" event.  But it starts with a "click" event.  So, when you do that action, the app gets notified of **two** events, and it has to figure out which makes sense.  I think mapApp handles that by throwing away brush events that cover only a tiny area -- at least that's what I usually do in my apps. One of the problems with all schemes is that they might depend on timing, so a delay/debounce criterion that works on one system might not work well on another.

In many ways, lower-level systems are easier to work with. When the programmer has to keep track of the event queue, they can do lots of clever things to avoid race conditions.

**Comment by dankelley** [comment]
PS an example of a tricky workaround is the last item at https://stackoverflow.com/questions/30527977/ggplot2-how-to-differentiate-click-from-brush ... but it is quite tricky because R/shiny doesn't tell you about mouse down/up events, so this person wrote javascript to monitor those things.

**Comment by dankelley** [comment]
I think I have addressed the issue of error messages at each character in "develop" commit 07dfb5043584f24c91eba019862210ba60651b4f.  (We ought to consider this a provisional fix until @j-harbin can assess it.)

What it does now is to only give a message if you've entered 7 characters.  I checked this by typing
```
1234567
```
and then I tried typing
```
3901851
```
and saw something interesting: if I typed slowly enough, when I got to `39018`, it drew the plot.   This indicates that float IDs can range in length from 5 to 7 (and possibly wider ... and so the code I wrote to declaring a 7-character limit might be wrong.  Again, I'd appreciate it if @j-harbin could think about this, and alter the code appropriately.  (Even if there *is* a valid 10-digit code, I think `mapApp()` will still take it. But it will tell you to limit yourself to 7 characters, until it finally "catches" the 10-digit ID.  I think @j-harbin might want to look at this.

**Comment by dankelley** [comment]
First, happy day before the first Sunday after the first full moon following the ecclesiastical spring solstice.

Second, I made a video to show that it seems to work now on the updated "develop".  I don't know whether this will work on @richardsc's machine, though, for there might be issues relating to speed of drawing, etc.  (Tangled event queues are tricky.)

You'll want to have sound on for the video, because I comment on some things. Also, if your eyes are not happy with tiny images, you might want to zoom your web browser before looking at the video.  (Why GH insists on wasting half the page to whitespace, I will never know.)

Note the "flash" at the end of the video, meaning it filled the screen twice, after my last interaction.  I think maybe @j-harbin and I should work on why that happens.  The way to debug such things is to put in lots of console messages so if we see 2 "redrawing" messages when we think there should be just 1 such message, then we can start to zero in on why that happens.  This sort of work is easier with 2 people.

https://user-images.githubusercontent.com/99469/163675745-9a8a5d09-5f5f-4d79-9023-99a3b61e3b97.mp4

**Comment by j-harbin** [comment]
I like your quick fix on this, Dan. I'm thinking that when the user types in a float ID (note, this is different than double clicking on a single float which also fills in the Float ID text box) they should be required to press the "enter" key on their keyboard to indicate they are done. This is a similar approach to something like Google. Having the user click an "enter" button on their key board instead of having an "Update" widget button on the app avoids crowing of the app . Of course the help pages would explain all of this. Let me know what you think about that and I can code that in.

**Comment by dankelley** [comment]
You should try seeing what happens if you type ENTER.  It might be ignored.  (For example, arrow keys are ignored.  So are SHIFT and CONTROL keys.  At least on mac.)

Also, how does the user know that they have to press ENTER?

I sort of favour doing what we discussed in the zoom yesterday: provide a button for the user to enter an ID.  If they click the button, a popup window appears asking them to enter the ID (and maybe the cycle).  And that window will have a close button, which the users will have to click.  (I think if they just click the GUI element to close a window, that also finalizes the entry.). That would be pretty clear.  That's what I plan on doing in my other argo app ... or at least, I'll try it, to see if it "feels" right.

**Comment by j-harbin** [comment]
@dankelley, you have made quite a good fix for this. Do you still want to me to add the 'enter' button, or are we satisfied with the way it currently works? I'm in favour of keeping it as it because it's working fine and it avoids crowding the interface with a new button.

**Comment by dankelley** [comment]
If this works OK, we don't need an "enter" button.  And I prefer not to have it, because that would be different from the rest of the app.

**Comment by j-harbin** [comment]
On that note, I'll close this issue but @richardsc can reopen if he feels this needs to be addressed further.
