### ISSUE TITLE
The server is not available

### ISSUE THREAD

**Issue by GC-OCEAN** [ArgoCanada/argoFloats#576]
I have tired the three servers, but no one is accessible to me

**Comment by richardsc** [comment]
Can you post the code that you tried? Also the results of doing `sessionInfo()`?

I get:
``` r
library(argoFloats)
i <- getIndex()
si <- subset(i, time=list(from=as.POSIXct('2022-06-16 00:00:00', tz='UTC'), to=as.POSIXct('2022-06-23 00:00:00', tz='UTC')))
#> Kept 2885 cycles (0.109%)
plot(si)
```

![](https://i.imgur.com/GZl4bWr.png)

<sup>Created on 2022-06-23 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by GC-OCEAN** [comment]
I tried getIndex(), but it failed. I can manually download the file https://data-argo.ifremer.fr/ar_index_global_prof.txt.gz by Chrome.

**Comment by GC-OCEAN** [comment]
By the way, I stay in China. All the servers are not available to me if I do not use VPN. Could you give me some suggestions?

**Comment by GC-OCEAN** [comment]
Is it possible to create a mirror for Chinese users? If it is possible, I will try to help make it.

**Comment by dankelley** [comment]
In R, can you try
```R
url <- "https://data-argo.ifremer.fr/ar_index_global_prof.txt.gz"
download.file(url, "ar_index_global_prof.txt.gz")
```
If you get something like below, then we will know that R can access files from that server.
```
trying URL 'https://data-argo.ifremer.fr/ar_index_global_prof.txt.gz'
Content type 'application/x-gzip' length 45907309 bytes (43.8 MB)
==================================================
downloaded 43.8 MB
```

As Clark says, we'd need to see exactly what you tried.  (Notice that Clark and I showed you exactly what we tried.)

As for making a mirror for Chinese access, that's not something I can help with.

**Comment by richardsc** [comment]
It seems a bit odd to me that you can visit the website and download the file, but the access seems to be blocked through R. But I don't know what kinds of restrictions are on your network in terms of web traffic versus automated requests done through protocols like `curl`. For example, when we build R packages, URLs that are included in the documentation are checked, and even those the sites themselves work, sometimes the checks fail because the web service is configured to deny non-browser access.

For access issues, I'd recommend you contact someone in the Argo China program, as China does operate their own DAC (data acquisition center). Perhaps the contacts [here](http://www.argo.org.cn/index.php?m=content&c=index&a=lists&catid=93) are useful.

Otherwise, it occurs to me that it might make sense for `getIndex()` to also accept a local file instead of requiring a download. It already does this if it finds a recently downloaded index file (in the correct spot). I'll open an issue to discuss this separately.

**Comment by richardsc** [comment]
Beyond the index file though, if you are having curl problems getting the index file, you'll also likely have problems getting the profile nc files.

**Comment by GC-OCEAN** [comment]
Surprisingly, after a day, this https server works for me suddenly. Thanks for your immediate and very useful help! It is a really great R package!

**Comment by richardsc** [comment]
Oh good news!

I'm going to go ahead and close the issue (though, leaving #577 open for now). We typically wait for reporters to close issue, but in this case it does seem like things are resolved for you (and were somewhat out of our control anyway).
