### ISSUE TITLE
Add server=NULL to getIndex()

### ISSUE THREAD

**Issue by j-harbin** [ArgoCanada/argoFloats#585]
If `server` = NULL, this will allow the download of a local file.

**Comment by dankelley** [comment]
For the wording, e.g. in docs, it is a reading of the local file, not a downloading :-)

**Comment by dankelley** [comment]
Done in commit 1616646783d2e63c53bf3801a9a7cac2c115f102 of "develop_kelley" branch.  That branch (as it is now, or with slight changes) will likely be merged into "develop" by some time next week.

**Comment by dankelley** [comment]
It looks as though other things came up, and I didn't get around to merging "develop_kelley" into "develop".  I've just done that, and am starting a local build-test sequence.  When that finishes, I'll push.  And, if after an hour or so the remote checks say things are OK, I'll post here again, asking the reporter, @j-harbin, if the issue has been addressed.  

My goal is to resolve this, one way or another.  It and other issues have been lingering for a long time, mainly because I seldom check on this package

**Comment by dankelley** [comment]
Dear reporter,

Do you think this issue (as defined by its title) has been addressed in the latest version of the "develop" branch? If so, please close the issue. If not, please add a comment explaining what remains to be done.

We use open issues as a sort of "to do" list for the project.

*Thanks!*

PS.  This is a standardized reply.

**Comment by dankelley** [comment]
I am closing this issue now, because (a) I think it has been handled, and (b) the reporter is a co-developer, who can be relied upon to reopen the issue if desired.
