### ISSUE TITLE
Add A Text Bubble to Video 1

### ISSUE THREAD

**Issue by j-harbin** [ArgoCanada/argoFloats#77]
@dankelley , here is a link that gives step by step how to add a text bubble to a youtube video.

https://www.youtube.com/watch?v=Jp7kl_FKShg

In this particular case, at the very beginning of video one when it shows

```R
library(devtools)
install_github('dankelley/argoFloats', ref='develop')
```

You could simply put a text box over that says

```R
library(devtools)
install_github('ArgoCanda/argoFloats', ref='develop')
```

**Comment by dankelley** [comment]
Thanks.  I tried to figure this out, but the interface is now different from the one shown in the instructional video you provided, so I did not make any progress.  Anyway, I added the new instructions in the "about this video" portion, and so that ought to be enough for people.

I propose we close the issue.  The ratio of effort to benefit is simply too high to justify leaving it open.
