### ISSUE TITLE
Add warning when lines intersect for polygon method

### ISSUE THREAD

**Issue by j-harbin** [ArgoCanada/argoFloats#78]
As discussed in our ftf, when I create an intersecting polygon (similar to shown below), and do the following code:

![polygon](https://user-images.githubusercontent.com/58750538/80401613-01345b80-8893-11ea-8181-dae840aca64d.jpg)

```R
library(argoFloats)
ai <- getIndex()
lonPoly <- c(-71.36, -75.15, -74.68, -72.94)
latPoly <- c(25.24, 27.11, 25.40, 28.47)
indexP <- subset(index, polygon=list(longitude=lonPoly, latitude=latPoly))
```

I receive the following error:

```R
Error in CPL_geos_op2(op, st_geometry(x), st_geometry(y)) : 
  Evaluation error: TopologyException: Input geom 1 is invalid: Self-intersection at or near point -74.025327790128358 26.555082577187338 at -74.025327790128358 26.555082577187338.
```

Which we expected due to the 'self-intersection'. As discussed, we should have our own warning from the `argoFloats` package when this happens.

**Comment by dankelley** [comment]
Fixed in "develop" branch commit  c9346a3c8d97d2b04527fafdfb35e44736cf1e49, but note that it generates an error, not a warning. 

It is an error because there is really no way to guess what the user wanted.  For example, in the sketch, we might guess that 2 and 3 were entered in the wrong order, but that really would just be a guess, and if we had more points, the guessing game would be a lot harder.  (This makes it a computationally complex problem, somewhat comparable to the "travelling salesperson" problem, which is the classic computational complex problem and is likely described very well in wikipedia and other places.)

It's better to get the user to decide how to fix the problem.  In some cases, they might have made a polygon by typing in coordinates, and it's very common to transpose digits while typing, and mathematical algorithms that look for simplicity of a curve would have a hard time detecting that.

Below is my test code:
```R
library(argoFloats)
if (!exists("ai")) # cache for debugging sped
    ai <- getIndex()
lonPoly <- c(-71.36, -75.15, -74.68, -72.94)
latPoly <- c(25.24, 27.11, 25.40, 28.47)
source("~/git/argoFloats/R/subset.R")
indexP <- subset(ai, polygon=list(longitude=lonPoly, latitude=latPoly))
```
and it makes output
```
Error: In subset,argoFloats-method(): self-intersecting, or otherwise invalid polygon
In addition: Warning message:
In subset,argoFloats-method(): Closing the polygon, since the first and last points did not match.
```
