### ISSUE TITLE
Video 3

### ISSUE THREAD

**Issue by j-harbin** [ArgoCanada/argoFloats#79]
As discussed in the ftf, it's a good idea to have a quick video showing:

A) The change from 'dankelley/argoFloats' to 'ArgoCanada/argoFloats'
B) User website

**Comment by dankelley** [comment]
I propose we do this today (Thu) at 1000h.  If one or more of you agrees before 0930h, I'll start a video chat at that time, inviting both of you.  The agenda would be:
1. 1000h-1015h: plan the video
2. 1015h-1020h: record the video and end the chat (because that's the way to end the video)

After the video, I'd convert it and put a draft on Dropbox, as usual, asking for a vote on upload before noon, with a potential upload at 1300h.

**Comment by dankelley** [comment]
Sorry for very late notice, but is 0900h OK?  We have a covid19/dalhousie meeting at 1000h.

**Comment by j-harbin** [comment]
Works for me!

**Comment by dankelley** [comment]
Video done, OK-d by both authors, and uploaded to https://youtu.be/lOvCrRDTmTs, so I'm closing this.  Thanks, @j-harbin
