### ISSUE TITLE
Error in downloadWithRetries

### ISSUE THREAD

**Issue by j-harbin** [ArgoCanada/argoFloats#82]
Hi All,

When I do the following code:

```R
library(argoFloats)
data('indexMerged')
profiles <- getProfiles(indexMerged)
```

I receive the following error:

```R
Error in downloadWithRetries(url = url, destdir = destdir, destfile = destfile,  : 
  failed to download from 'ftp://ftp.ifremer.fr/ifremer/argo/dac/aoml/4900845/profiles/MD4900845_086.nc', after 3 retries  
```

Do you guys receive this error as well?

**Comment by dankelley** [comment]
I emptied out my `~/data/argo` directory, did
```R
library(argoFloats)
data('indexMerged')
profiles <- getProfiles(indexMerged)
```
and got as below.  So, the same thing at the end but @j-harbin did you get the initial lines as I got?  (I'm assigning to me, since I wrote the code.)
```
> library(argoFloats)
> data('indexMerged')
> profiles <- getProfiles(indexMerged)
Error in curl::curl_download(url = url, destfile = destination, quiet = quiet,  : 
  Given file does not exist
Error in curl::curl_download(url = url, destfile = destination, quiet = quiet,  : 
  Given file does not exist
Error in curl::curl_download(url = url, destfile = destination, quiet = quiet,  : 
  Given file does not exist
Error in curl::curl_download(url = url, destfile = destination, quiet = quiet,  : 
  Given file does not exist
Error in downloadWithRetries(url = url, destdir = destdir, destfile = destfile,  : 
  failed to download from 'ftp://ftp.ifremer.fr/ifremer/argo/dac/aoml/4900845/profiles/MD4900845_086.nc', after 3 retries
```

**Comment by dankelley** [comment]
Hm, I turned on debugging and got as below.  Then I used a browser to look at the directory and, indeed, the file we are looking for *does not exist.*

Maybe the filename changed. 

```R
 profiles <- getProfiles(indexMerged, debug=5)
getProfiles() {
  index[["ftpRoot"]]: ftp://ftp.ifremer.fr/ifremer/argo/dac
  index[["file"]] [1:39]: aoml/4900845/profiles/MD4900845_086.nc, aoml/4900845/profiles/MD4900845_087.nc, ..., meds/4901140/profiles/MD4901140_134.nc, meds/4901140/profiles/MD4901140_138.nc
  urls [1:39]: ftp://ftp.ifremer.fr/ifremer/argo/dac/aoml/4900845/profiles/MD4900845_086.nc, ftp://ftp.ifremer.fr/ifremer/argo/dac/aoml/4900845/profiles/MD4900845_087.nc, ..., ftp://ftp.ifremer.fr/ifremer/argo/dac/meds/4901140/profiles/MD4901140_134.nc, ftp://ftp.ifremer.fr/ifremer/argo/dac/meds/4901140/profiles/MD4901140_138.nc
getProfileFromUrl(url="ftp://ftp.ifremer.fr/ifremer/argo/dac/aoml/4900845/profiles/MD4900845_086.nc", destdir="~/data/argo", destfile="(missing)", ...) {
  inferred destfile="MD4900845_086.nc" from url.
downloadWithRetries(
    url='ftp://ftp.ifremer.fr/ifremer/argo/dac/aoml/4900845/profiles/MD4900845_086.nc',
    destdir='~/data/argo',
    destfile='MD4900845_086.nc',
    mode='wb', quiet=FALSE, force=FALSE,
    retries=3) {
Error in curl::curl_download(url = url, destfile = destination, quiet = quiet,  : 
  Given file does not exist
Error in curl::curl_download(url = url, destfile = destination, quiet = quiet,  : 
  Given file does not exist
Error in curl::curl_download(url = url, destfile = destination, quiet = quiet,  : 
  Given file does not exist
Error in curl::curl_download(url = url, destfile = destination, quiet = quiet,  : 
  Given file does not exist
Error in downloadWithRetries(url = url, destdir = destdir, destfile = destfile,  : 
  failed to download from 'ftp://ftp.ifremer.fr/ifremer/argo/dac/aoml/4900845/profiles/MD4900845_086.nc', after 3 retries
```

**Comment by j-harbin** [comment]
Yes, I also received the initial lines that you got. I receive the exact same error.

**Comment by dankelley** [comment]
OK, so I tried
```R
library(argoFloats)
indexAll <- getIndex(file="merged")
indexMerged <- subset(indexAll, circle=list(longitude=-77.06, latitude=26.54, radius=300))
```
and then tried this again.  I get the same error.

So, I did
```R
indexMerged@metadata
```
and got (I'm omitting other things)
```
$server
[1] "ftp://usgodae.org/pub/outgoing/argo"

$ftpRoot
[1] "ftp://ftp.ifremer.fr/ifremer/argo/dac"
```
which is interesting, because those are two different servers.

I think this is a case where @j-harbin could help out, by trying two things:
1. do the docs tell us whether to use what we are calling `server` or what we are calling `ftpRoot`?
2. run the `getProfiles()` with `debug=4` and take a note of the file it's trying to download, and then try to download manually from both sites, to see if one is right.  You can try a download in firefox by entering the `ftp:` information into the location bar, and likely you can do the same with chrome etc.  You can also use `Finder/Go/Connect to Server`.  There are other ways too ... it would be good for you to try them out, because this kind of detective work comes up a lot.

**Comment by dankelley** [comment]
Also, @j-harbin, it would be great if you could figure out (from docs) what the letters on the start of the files mean.  The name of the file we are having trouble with starts with `MD`.  We don't have any such file in ftp://ftp.ifremer.fr/ifremer/argo/dac/aoml/4900845/profiles; instead, we have filenames starting with `BR`, `D`, and `SD`.  So, maybe (just guessing, and I don't like guessing!) an `MD` file is sometimes also called an `SD` file.

But it could be that the US server has the file we want.

Some hints here, @j-harbin ... and a bit of insight into how important detective work is in understanding data files and data repositories.

**Comment by j-harbin** [comment]
Using section 4.1 of The Argo User's Manual (references below) I have determined that:

1)  *Core argo*  file names are in the format: <R/D><FloatID>_<XXX><D>.nc , where the initial R indicates Real-Time data the initial D indicates Delayed-Mode data XXX is the cycle number the second D indicates a descending profile (profiles without this D are collected during ascent). 

2) *BGC-Argo* file names are in the format B<R/D><FloatID>_<XXX><D>.nc, where 
 B : B-Argo file prefix
 <R/D><FloatID>_<XXX><D>.nc : identical to Core-Argo file naming convention

3) *Merged* file names have the format M<R/D><FloatID>_<XXX><D>.nc, where
 M : merged B-Argo file prefix
 <R/D><FloatID>_<XXX><D>.nc : identical to Core-Argo file naming convention

All of this to say, it doesn't mention anything about `SD` files, however, I am continuing my detective work. 

Reference

Carval, T., Keeley, B., Takatsuki, Y., Yoshida, T., Loch, S., Schmid, C., Goldsmith, R., Wong, A., McCreadie, R., Thresher, A. and Tran, A., 2015. Argo User's Manual, Version 3.2. December 29th 2015.[SUPERSEDED].

**Comment by j-harbin** [comment]
I think a vchat would be useful.

**Comment by j-harbin** [comment]
Closing this issue as we determined that we should be using the `server` and not the `ftpRoot`

**Comment by dankelley** [comment]
FYI, I have documented this change (see the Details section of https://argocanada.github.io/argoFloats/reference/getProfiles.html) and updated both the "master" and "develop" branches. 


Oh, and I have also double-checked the new behaviour, by removing the existing files in `data/argo` and doing
```R
library(argoFloats)
data(indexMerged)
p <- getProfiles(indexMerged)
```

**Comment by dankelley** [comment]
I reopened this because it seems to be related to #82

**Comment by dankelley** [comment]
A checklist (I will click as I do them, but not as I upload to GH; thus, this is diary for me as I work on this) -- 
1. [ ] make the 'metadata' item called 'ftpRoot' store both places (actually, as many places as the file holds)
2. [ ] make 'summary' show both (or all)
3. [ ] rebuild the datasets, but *not* by rerunning code in `create_data`, because that would start with fresh data, which we do *not* want (given that we have tests based on the index not changing)

**Comment by dankelley** [comment]
@j-harbin I have rewritten `[[` and some other low-level things.  I have *not* recoded `getProfiles()` as we had discussed (trying two servers) for the reason that we discussed (uncertainty, to someone looking at the files later, as to where they came from).

However, when I 
1. clean out all the files in `~/data/argo` (or just copy the old `argo` to `argoOld` or something, to avoid losing a lot of already-downloaded files)
2. run `issues/82/82a.R`
I no longer get an error.

So, can you do the two steps I've listed above, and report your results?

PS. of course `82a.R` is based on https://github.com/ArgoCanada/argoFloats/issues/82#issue-610143317 and the idea of this new `issues` directory is that we set up clean code that will test bugs.

**Comment by j-harbin** [comment]
Hi Dan,

I can confirm when I complete those tasks as well, I no longer receive an error.

**Comment by dankelley** [comment]
Thanks.  So, now we have the question of what to do.  If I had made issue, I'd close it now, knowing that it can be reopened if the problem arises again.

However, you have a better memory than I, and so perhaps it might make sense to leave this open until sometime next week ... if you can remember to close it then :-)

Note: if `getProfiles()` cannot download a file now, it gives an error message suggesting to refresh the index by using `getIndex(...,age=0)`.  But I really don't know if that was the problem.  It's hard to debug a problem that seems not to exist anymore.

I guess we *could* use git to recover the source code from a few days ago to try to make the bug happen again, but the intervening code changes were large enough that it would be hard to learn much from that.  Besides, there's no way I want the code to go back to 8 days in the past, because the things that were done in the meantime were very helpful.  I am a "eye on the road, not on the mirror" kinda guy.
