### ISSUE TITLE
Should be able to handle "S" (synthetic) profiles for BGC floats

### ISSUE THREAD

**Issue by richardsc** [ArgoCanada/argoFloats#93]
TIL about "S" profiles, or "synthetic" profiles for BGCArgo floats. I still don't know all the details, but this is a good reference (with good linked reading):

http://www.argodatamgt.org/Data-Mgt-Team/News/BGC-Argo-synthetic-profiles-distributed-on-GDAC

https://archimer.ifremer.fr/doc/00445/55637/

Indeed the Coriolis GDAC is producing these files, along with an index:
![image](https://user-images.githubusercontent.com/233584/82001062-93c55080-9630-11ea-9f4d-148b02bbc6e7.png)

@dankelley pointed out that the USGODAE GDAC doesn't have the same, and I notice a comment at the bottom of the first link above that says:

> The US-GDAC is working on a synchronization of synthetic profiles from Coriolis GDAC.

And also:

> The existing M-prof (merged BGC profiles) is to be replaced by S-prof.
> The distribution of M-prof profiles will stop in December 2019.

**Comment by dankelley** [comment]
Thanks.  That's interesting about the "will stop in Dec 2019" part, given that this is May 2020.

I think our code will need to accept both "merged" and "synthetic" files.  That means we'll need to change quite a lot of documentation, and an unknown amount of code.  

Today, I will try a download of one of these new `.nc` files, to see if `oce::read.argo()` can read it.  If they have changed the names of important metadata, we might need mods to `oce`.  That will pose a challenge for `argoFloats` users who are not set up to compile packages (including, at the moment, @j-harbin), so I hope things will go okay.

In principle, I *love* the idea of this format.  It strikes me as crazy that 1/2 the "merge" files have two columns, with the second one being almost entirely `NA`.  Not only does this add to server and bandwidth costs, it complicates code, e.g. we've had several bugs that arose from this.  As I understand it, this new format will have just one column per profile, which is helpful.

I am assigning myself, since the first steps may require going into `oce::read.argo()` code, even just as a check.  However, if that works, then we won't need any changes to `oce`, at which point I will change the assignment to @j-harbin.  If it fails, I'll need to check further on

* Is the failure because `ncdf4` cannot read the `.nc` files?  That will be a real problem because my impression is that `ncdf4` is the best package for reading netcdf.
* Is the failure because `oce` expects a different data layout (e.g. metadata names) than in the new `.nc` files? In this case, I would be inclined to port `oce:read.argo()` into `argoFloats`, so fixes can be made there (thus not requiring users to set up the package-compiling toolchain).  I do not want to do a forced CRAN release of a patched `oce`, just for one data type, since doing so locks out other CRAN releases for a long time, to the detriment of non-argo users.

**Comment by dankelley** [comment]
I've made some progress (not committed to GH) but will be interrupted this morning with some other things, so I'll return to it this afternoon.  My changes are causing errors through ripple effects, and that's so I have not pushed to GH, and why I hereby ask that others do not alter the `R/get.R` code until I make another comment here.

**Comment by richardsc** [comment]
Maybe I'm missing something, but it seems like oce is able to read/handle these S files without problems ... ? At least, the two examples given here:

ftp://ftp.ifremer.fr/ifremer/argo/dac/coriolis/6901585/profiles/SD6901585_001.nc

ftp://ftp.ifremer.fr/ifremer/argo/dac/coriolis/6901585/6901585_Sprof.nc

```r
library(oce)
d <- read.oce('6901585_Sprof.nc')
plotProfile(as.ctd(d, profile=50), xtype='oxygen')
```

**Comment by dankelley** [comment]
Yes, my tests show oce will handle it.  I've been in meetings for the morning but will clean things up in the aft.  I am going to make a new built-in dataset that is of the synth variety.

Oddly, the construction of full URLs that @j-harbin and I figured out before for ifremer does not work.  Either we were wrong and had not tested it, or it has changed. (The diff, at least as we previously thought, was that the usgodae had "dac" in the URL, and ifremer did not ... or vice versa; no point in remembering which because all that matters is the code!)

**Comment by dankelley** [comment]
I added (to "develop") a `indexSynthtic` file, and the following (from the test suite) indicates that the "hits" we get by doing the circle subset are the same as a few weeks ago, when we built `indexMerged`.
```R
test_that("indexMerged and indexSynthetic files correspond", {
          m <- indexMerged[["file"]]
          s <- indexSynthetic[["file"]]
          ## MR and MD files both become SD files
          expect_equal(gsub("MR", "SD", gsub("MD", "SD", m)), s)
})
```

**Comment by richardsc** [comment]
Something seems wrong, since I just re-built and tried:
```r
> library(argoFloats)
data(indexSynthetic)
Warning message:
In data(indexSynthetic) : data set ‘indexSynthetic’ not found
```

**Comment by dankelley** [comment]
Can you re-download and try?  I get as follows (with "master" a05353886577c930f0b9a75916663f55e3c10cee, which merged "develop" 1cb60f11c9a1283a8bd9557f07fba20fdd797d03 a few minutes ago).

**Comment by dankelley** [comment]
Sorry, please re-download either "master" or "develop".  I had forgotten to do a
```
git add -f
```
which is needed because we gitignore RDA files.

PS. I discovered this on restarting the appveyor build.  That just refuses to notice `git push` operations.  As for travisCI, it is broken lately because their linux is messed up.

**Comment by richardsc** [comment]
Yes, I was just about to add that I think that was what the problem was :)

**Comment by j-harbin** [comment]
Dear reporter,

Do you think this issue (as defined by its title) has been addressed? If so, please close it. If not, please add a comment explaining what remains to be done. Thanks!

PS. This is a standardized reply.
